In [5]:
using Julog

clauses = @julog [
  ancestor(sakyamuni, bodhidharma) <<= true,
  teacher(bodhidharma, huike) <<= true,
  teacher(huike, sengcan) <<= true,
  teacher(sengcan, daoxin) <<= true,
  teacher(daoxin, hongren) <<= true,
  teacher(hongren, huineng) <<= true,
  ancestor(A, B) <<= teacher(A, B),
  ancestor(A, C) <<= teacher(B, C) & ancestor(A, B),
  grandteacher(A, C) <<= teacher(A, B) & teacher(B, C)
]
goals = @julog [ancestor(sakyamuni, huineng)]; # List of terms to query or prove
sat, subst = resolve(goals, clauses);
subst
dump(clauses)

Array{Clause}((9,))
  1: Clause
    head: Compound
      name: Symbol ancestor
      args: Array{Term}((2,))
        1: Const
          name: Symbol sakyamuni
        2: Const
          name: Symbol bodhidharma
    body: Array{Term}((0,))
  2: Clause
    head: Compound
      name: Symbol teacher
      args: Array{Term}((2,))
        1: Const
          name: Symbol bodhidharma
        2: Const
          name: Symbol huike
    body: Array{Term}((0,))
  3: Clause
    head: Compound
      name: Symbol teacher
      args: Array{Term}((2,))
        1: Const
          name: Symbol huike
        2: Const
          name: Symbol sengcan
    body: Array{Term}((0,))
  4: Clause
    head: Compound
      name: Symbol teacher
      args: Array{Term}((2,))
        1: Const
          name: Symbol sengcan
        2: Const
          name: Symbol daoxin
    body: Array{Term}((0,))
  5: Clause
    head: Compound
      name: Symbol teacher
      args: Array{Term}((2,))
        1: Const
          name: Symbo

So

DataKanren
minikanren uses function calls as the heads of rules. This is also a discussion that Warren made in his book that was very intertesting


pattern matching = Subst -> Subst

The essential character of pattern matching.
term -> Option BindingDict

term -> Bindings -> Bindings


# A matcher is a function which takes 3 arguments
# 1. Expression
# 2. Dictionary
# 3. Callback: takes arguments Dictionary × Number of elements matched

Datalog rhs is in essence a pattern match. A nondetemrinstic pattern match over a database. bindings -> db -> bindings. The database takes the place of the term.


You only need the bindings in context if you're doing nonlinear pattern matching. But that is part of the beauty of datalog

pattern matching combinators. These are the dynamically typed more interpeted flavor of recursors.

Lit, Plus, Times, patvar 
def lit(n):
    return lambda (t,b):
def patvar(name):
    def res(t,bind):
        if name in bind:
            if t in bind:
                return bind
            else:
                throw PatternFailure
        else:
            bind[name] = t
            return bind
    return res
    
def plus(pa,pb):
    def res(t,bind):
        if t.head == "plus" of if t isinstance(Plus):
             bind = pa(t.a, bind)
             bind = pb(t.b, bind)
        else:
             throw PatternFailure
        
def match(pat,t):
    try:
        bind = {}
        return pat(t,bind)
    except PatternFailure:
        return None
        

pattern matching over 
(db, bind)

def pdf(name):
    def searcher(*args):
        def res(db, bind):
            if (name, len(args)) in db:
                
            else:
                []

database is a mapping from name,arity to dataframes



database -> Binding -> [Binding]

database -> state -> [state]
state may include a counter for example


(db -> state -> [state], ddb -> state -> [state])
"automatic differentiation"
(db, ddb), (state, dstate) -> [(state, dstate)]
why do I need dstate?

Is reverse mode useful?
may need to refactor this

db -> state -> [state], (db, ddb, state) -> [state] 


lit1(name)(x) = 
               if x is const
                   (db,state) -> if x in db[name] [state] else []
               if x is var
               
                   (db, state) -> 
                             if x boundin state 
                                if state[x] in db[name]
                                 [state] else []
                              else 
                                 [ extend(state, x, v) for v in db[name] ]
                                 
lit2(name)(x,y)
lit(name)(*args) = 



fresh(f) = (db,state) -> f(state.counter)(db, state.counter += 1)
fresh(f) = (db, state) -> begin 
    state.push(unknown)
    f(len(state))(db,state)
    end
    
    
database

conj is basically bind?

conj( g1, g2  ) = (db,state) -> 
    for s2 in g1(db,state)
        g2(db,s2)
    
    
   end
   
conj is basically multiplication with regards to derivative
dconj(g1,g2) = conj(g1[0], g2[1]) + conj(g1[1], g2[0]) 
    

An applier 
litapply(name)(x,y) = 

impl Applier for
impl 

implies( hyp, conc ) = 

type tupn =
   Tup1 : int Array
   Tup2 : (int * int) Array

tupn HashMap(String).t

instance Applier name '(a,b)

instance Serachable '(Int, Var)
instance Searchable '(Var, Var)
instance Searchable '(Int, Int)
    search db name id = lookup db id  


moving the size to runtime.
(int array array) HashMap( Tuple(string. int) )

finally tagless maybe could help?


tuple(string,schema)

where schema is gadt key to table.

taggedarray list

type taggedarray = 
  | Ints : int array -> taggedarray
  | Bools : bool array
  | string : string array
  

python dict
db[(string, int)] = numpy array or dataframe

(db, ddb, state) ->  



In [2]:
import Pkg; Pkg.add("Julog")

    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed Julog ─ v0.1.10
    Updating `~/.julia/environments/v1.6/Project.toml`
  [5d8bcb5e] + Julog v0.1.10
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [5d8bcb5e] + Julog v0.1.10
Precompiling project...
  ✓ Julog
1 dependency successfully precompiled in 4 seconds (223 already precompiled)


In [ ]:
#
struct Rel
    stable
    inc
    fresh
end

struct Bind
    rel
    ins::Vector{Int64 => Symbol}
    outs
end
struct CheckEq
    a::Symbol
    b::Symbol
end
struct Yield
    args
end
# should semi naive translation happen before instructions? Before intepretation?
# I suppose it should.

# topological sort also




function interp(insns, buf)
    insn = insns[1]
    insns = insns[2:end]
    if insn isa Bind
        quote
            for ( $ins... ) in $rel.stable
                
            end
        end
    elseif insn isa CheckEq
        quote
            if $(insn.a) == $(insn.b)
                $(  interp(insns) )
            end
        end
    elseif insn isa Yield
        :( push!($buf, $(insn.args) ) )
    end
end


# stratified negation






In [7]:
#import Pkg; Pkg.add("DataFrames")
#using DataFrames
#ttps://github.com/frankmcsherry/blog/blob/master/posts/2018-05-19.md

edge = [(:a, :b), (:b, :c), (:c, :b), (:c, :d) ]

reachable = []

dedge = edge
dreach = copy(edge)

# reachable := edge, reachable


dreach1 = [  (x,z)  for (x,y) in edge for (y1,z) in dreach if y == y1 ]
dedge1 = []
dedge = dedge1
dreach = dreach1

reachable = dreach ∪ reachable


4-element Vector{Any}:
 (:a, :c)
 (:b, :b)
 (:b, :d)
 (:c, :c)

Datalog.

a = []
function rule1(a,da,b,db,c,dc)
    for (x,y,z) in a
      for (a,b,c) in b # possibly index into b instead.
      
      end
      end
end


struct Rel
    name:Symbol
    vars::Vector{symbol}
end

struct Rule
    head::Rel
    thing:Vector{Rel}
end

The da are with respect to when though? Since the ladst time we updated this one?
I guess if we wrote this thing as 

dconj(a,b)
    for 
    (c, dc)
end

compose(a,b)
    
    return (c, 
    (da,db) -> 
    da * b \cup
    b * da \cup
    da * db 
     )
end

Is the matrix view helpful?

"Auatomatic finite differencing"

Using conitnuations like this is ultamitely silly. You want to just mutate.

do
    drel = Op(rels, drel)
    rel = rul \cup drel
while drel not empty


function rule(a,da)
   

Naive evaluation
for (x,y,z) in a
    
end

@datalog a(x,y,z), b(z,p,q), 

bind(a, (x,y,z) ->  bind(b, (x1,y1,z1) -> if x1 == x && ...  )
q(X,Z) :- a(X,Y), b(X,Z)

Ok no shared variables. That's a nicety
q(X,Z) :- a(X,Y), b(X1,Z), X = X1.

q = [  (x,z) for (x,y) in a for (x1,y) in b if x == x1 ]

"Modes" are indexing choices?

Ok so niave literal reading
q(x,y).
q(X,Y) :- p().

Sequential. or in parallel.

dq1 = 
dq2 = 
dq3 = 
dq4 = 

return union(dq1,2,dq3,dq4

becomes

q = []
q = [   ]  \cup q 

Should I record an index for each line of where dq starts? Or maybe I just know it is dq + dq + dq.
Or maybe I put it in a worklist. Everyone who depends on q. But they depend on multiple things.

https://www.stephendiehl.com/posts/exotic04.html stephen diehl on souffle



Alessandro showed an interesintg analogy.
If we use the egraph as our database of facts, we can apply datalog style bottom up reasoning to it by using multipatterns.
Is this how uZ3 works? No, I think


It would be neat to use DataFrames?

Datalog for DataFrames



In [24]:
goals = @julog [grandteacher(X, Y)];
sat, subst = resolve(goals, clauses);
subst
goals

1-element Array{Compound,1}:
 grandteacher(X, Y)

In [6]:
using Metatheory



┌ Info: Precompiling Metatheory [e9d8d322-4543-424a-9be4-0cc815abe26c]
└ @ Base loading.jl:1278


In [13]:
G = EGraph(:a)
t2 = addexpr!(G, :b)
merge!(G, t2.id, 1)
in_same

2

In [45]:
comm_monoid = @theory begin
    a * b => b * a
    a * 1 => a
    a * (b * c) => (a * b) * c
end

dump(comm_monoid)

Array{Rule}((3,))
  1: Rule
    left: Expr
      head: Symbol call
      args: Array{Any}((3,))
        1: Symbol *
        2: Symbol a
        3: Symbol b
    right: Expr
      head: Symbol call
      args: Array{Any}((3,))
        1: Symbol *
        2: Symbol b
        3: Symbol a
    expr: Expr
      head: Symbol call
      args: Array{Any}((3,))
        1: Symbol =>
        2: Expr
          head: Symbol call
          args: Array{Any}((3,))
            1: Symbol *
            2: Symbol a
            3: Symbol b
        3: Expr
          head: Symbol call
          args: Array{Any}((3,))
            1: Symbol *
            2: Symbol b
            3: Symbol a
    mode: Symbol rewrite
  2: Rule
    left: Expr
      head: Symbol call
      args: Array{Any}((3,))
        1: Symbol *
        2: Symbol a
        3: Int64 1
    right: Symbol a
    expr: Expr
      head: Symbol call
      args: Array{Any}((3,))
        1: Symbol =>
        2: Expr
          head: Symbol call
          arg

In [ ]:
#https://github.com/AlgebraicJulia/Catlab.jl/blob/master/src/theories/Monoidal.jl

@theory MonoidalCategory{Ob,Hom} <: Category{Ob,Hom} begin
  otimes(A::Ob, B::Ob)::Ob
  otimes(f::(A → B), g::(C → D))::((A ⊗ C) → (B ⊗ D)) ⊣
    (A::Ob, B::Ob, C::Ob, D::Ob)
  @op (⊗) := otimes
  munit()::Ob

  # Monoid axioms.
  (A ⊗ B) ⊗ C == A ⊗ (B ⊗ C) ⊣ (A::Ob, B::Ob, C::Ob)
  A ⊗ munit() == A ⊣ (A::Ob)
  munit() ⊗ A == A ⊣ (A::Ob)
  (f ⊗ g) ⊗ h == f ⊗ (g ⊗ h) ⊣ (A::Ob, B::Ob, C::Ob, X::Ob, Y::Ob, Z::Ob,
                                f::(A → X), g::(B → Y), h::(C → Z))

  # Functorality axioms.
  ((f ⊗ g) ⋅ (h ⊗ k) == (f ⋅ h) ⊗ (g ⋅ k)
    ⊣ (A::Ob, B::Ob, C::Ob, X::Ob, Y::Ob, Z::Ob,
       f::(A → B), h::(B → C), g::(X → Y), k::(Y → Z)))
  id(A ⊗ B) == id(A) ⊗ id(B) ⊣ (A::Ob, B::Ob)
end


In [43]:
dump(:(f::Int64))

Expr
  head: Symbol ::
  args: Array{Any}((2,))
    1: Symbol f
    2: Symbol Int64


In [60]:
clauses = @julog [
  typ(ob, typ) <<= true,
  typ(hom(A,B), typ) <<= typ(A, ob) & typ(B, ob), 
  typ(id(A), hom(A,A)) <<= true,
  typ(comp(F,G), hom(A,C)) <<= typ(F, hom(A,B)) & typ(G, hom(B,C)),
  typ(otimes(A,B), ob) <<= typ(A,ob) & typ(B, ob),
  typ(otimes(F,G), hom(otimes(A,B), otimes(C,D))) <<= typ(F, hom(A,C)) & typ(G,hom(B,D)) 
]
# hmm, I'm supressing all the typ(a,ob).
goals = @julog [typ(id(a), T) , typ(comp(id(A), id(B)), T2), typ(otimes(id(C),id(D)), T3 )];
sat, subst = resolve(goals, clauses);
subst

# So As long as I'm inferring types, I don't think


1-element Array{Any,1}:
 {T => hom(a, a), T2 => hom(A, A), D => A, B => A, T3 => hom(otimes(A, A), otimes(A, A)), C => A}

In [ ]:
@theory
    a * a ~~> (sub -> sub[:a] * sub[:a] * dict[:a])  

end

In [62]:
clauses = @julog [
  typ(ob, typ) <<= true,
  typ(hom(A,B), typ) <<= typ(A, ob) & typ(B, ob), 
  typ(id(A), hom(A,A)) <<= true,
  typ(comp(F,G), hom(A,C)) <<= typ(F, hom(A,B)) & typ(G, hom(B,C)),
  typ(otimes(A,B), ob) <<= typ(A,ob) & typ(B, ob),
  typ(otimes(F,G), hom(otimes(A,B), otimes(C,D))) <<= typ(F, hom(A,C)) & typ(G,hom(B,D)) 
]
dump(clauses)

Array{Clause}((6,))
  1: Clause
    head: Compound
      name: Symbol typ
      args: Array{Term}((2,))
        1: Const
          name: Symbol ob
        2: Const
          name: Symbol typ
    body: Array{Term}((0,))
  2: Clause
    head: Compound
      name: Symbol typ
      args: Array{Term}((2,))
        1: Compound
          name: Symbol hom
          args: Array{Term}((2,))
            1: Var
              name: Symbol A
            2: Var
              name: Symbol B
        2: Const
          name: Symbol typ
    body: Array{Term}((2,))
      1: Compound
        name: Symbol typ
        args: Array{Term}((2,))
          1: Var
            name: Symbol A
          2: Const
            name: Symbol ob
      2: Compound
        name: Symbol typ
        args: Array{Term}((2,))
          1: Var
            name: Symbol B
          2: Const
            name: Symbol ob
  3: Clause
    head: Compound
      name: Symbol typ
      args: Array{Term}((2,))
        1: Compound
          na

In [59]:
for (k,v) in collect(subst[1])
    dump(k)
    dump(v)
end

Var
  name: Symbol T
Compound
  name: Symbol hom
  args: Array{Term}((2,))
    1: Const
      name: Symbol a
    2: Const
      name: Symbol a
Var
  name: Symbol T2
Compound
  name: Symbol hom
  args: Array{Term}((2,))
    1: Var
      name: Symbol A
    2: Var
      name: Symbol A
Var
  name: Symbol D
Var
  name: Symbol A
Var
  name: Symbol B
Var
  name: Symbol A
Var
  name: Symbol T3
Compound
  name: Symbol hom
  args: Array{Term}((2,))
    1: Compound
      name: Symbol otimes
      args: Array{Term}((2,))
        1: Var
          name: Symbol A
        2: Var
          name: Symbol A
    2: Compound
      name: Symbol otimes
      args: Array{Term}((2,))
        1: Var
          name: Symbol A
        2: Var
          name: Symbol A
Var
  name: Symbol C
Var
  name: Symbol A


Why does he need the root? There is not root?



It got me all the solutions eagerly... What.


Using the DijsointSet for unification. We could make a varaint of disjoint set that uses a persistent array underneath.

Unification is breaking up the term universe (herbrand universe) into disjoint sets oif terms.
This is a huge thing that can only be talked about implcility.

Or is it a term universe with variable slots?

Still, if we have a set of equations
f(~a,b) == f(~c, b)

Add to disjointset even compound terms or only when hit atom?
set_equal( t1,t2 ) ?

The hash cons is just an optimization to avoid traversing terms?

Anti-confurence f(x) = f(y) => x = y . Closure over injectivity.

There is a certain kind of symmettry between the egraph problem and the unification problem

Var(a) == Var(c)
b == b
f



occurs_check(IntDisjointSet) post hoc or pre hoc?




unification for Catlab


Well, i already did this in my minikanren exploits.
We could use JuLog

[
 id => id(~a)
 sigma => sigma(~A,~B)
 ...
 
]


Prolog + egraphs.

If smt is sat + egraphs
Then prolog search + egraphs should be no problem in principle.
Prolog takes uniifcation as a base construct, Egraphs are similar in many repsects to unification.
E-Graphs work over ground terms though.

Swap in persistent structures?
vs. just copying.
Copying might be fast.

I wonder how good tabling might be at just axiomatizing equality as a predicate
A == A.
A == B :- B == A.
A == C :- A == B, A == C.


I wonder how hard it would be to build an egraph as a library?
We already have natural union find.
Making fresh Ids is easy

enode(N , Terms )


eclass(f(a,b) , C ) :- eclass( g(q) , C).
eclass( f(A,B), C ) :- eclass( f(A', B), C  ), eclass( A, D  ), eclass(A', D') % congurence


f(a) = g(b) expands to

You need to assert all facts in the same context.
eclass(g(b), C) :- eclass(g(b), D), D = C.


eclass(f(a), C), eclass(g(b), C), ... , eclass(Q, C).




egraph(Nodes,  , Parents ) :-


% equalty is a special "tabled" predicate
f(x,y) == g(z,w). % assert ground equalities.
f(A) == g(A). % pattern match and instantiate

What if you could smush together scryer and egg.


A == B :- 

p( , ) :- A === B, 

Or should I build prolog into the e matcher?
Collect matches

typ(F) ~ hom(A,B)  => F == id(F) . F


The catlab syntax is SMART because it has the minimal annotation to make it unambiguously typed. This is for user reasons, but it is also good for automation reasons. We don't chunk up

A birdirectional type checking thing woud have top level annotations

Julog
Shouold typ work on unleaborated terms or no?
Yes, the point free categroicval style lets us think about elaboration without worrying about binding issues.
That's nice. (Not that binding issues are like the end all be all of problems. Cody would be inclined to sayu that's the least of your owrries.)

typ(comp(F,G), hom(A,B)) :- typ(F, hom(A,B), typ(G, hom(B,C))
typ(comp(A,B,F,G), hom(A,B) ). 



I could cut every predicate? That's indicative that i don't really need prolog search. 
typ(comp() , ) :- !, 

elab(id, id(A)).
elab( comp(F,G) , comp(A,B,F',G')) :- elab(F,F'), elab(G,G'), typ(comp(F,G) 
 
 

elab( lam(X, ) , lam(X,A, ) , FVar)

check() :-  
infer() :- !, infer
 
 Prolog typechecker
 https://news.ycombinator.com/item?id=15583515
 
 https://www.cs.kent.ac.uk/pubs/2012/3136/content.pdf smt solver in prolog
 Its also nice that it expresses about the naivest methods of smt solving possible
 
 There is a dumber version of congurence closure. some kind of for loop
 

In [21]:
x = Ref{Any}(:a)
x[] = x

x[] === x

x[] isa Ref


true

In [28]:
Ref{Any}()

Base.RefValue{Any}(#undef)

In [30]:
function newvar()
    x = Ref{Any}()
    x[] = x
    x
end

newvar (generic function with 1 method)

In [23]:
function canon(x)
    while x isa Ref && x[] != x # could do some small path compression here
        # temp = x
        x = x[]
        # temp[] = x[] 
    end
    return x
end
    

function unify(x, y)
    x = canon(x)
    y = canon(y)
    if x === y
        ()
    elseif x[] isa Ref
        x[] = y
    elseif y[] isa Ref
        y[] = x
    else
        return false
    end
end

unify (generic function with 1 method)

In [69]:
DisjointSets{Union{Symbol,Int}}()

#= function unify!(s, x, y)
    x = find_root!(s,x)
    
end =#
struct Var
    id::Int
end
# let's not even bother renaming it though?
unify!(s,x,y) = union!(s, x, y)
# This is for datalog queries. However, What about terms?



function foo(s,x,y,c)
    union!(s, x,:a)
    union!(s, y,:c)
    greg(s)
    larry(s, :a)
end


unify! (generic function with 1 method)

In [ ]:
function unify!(d, t1::Var,t2)
    set_equal(d, t1, t2)
    return true
end

function 

function unify!(d, t1, t2)
    t1.head != t2.head && length(t1.args) != length(t2.args) && return nothing
    for t1,t2 in zip(t1.args, t2.args)
        !unify!(d, t1, t2) && return false
    end
    return true
end
    
unify(t1,t2) = unify!(DisjointSet{Union{Var,Term}}(), t1, t2)

    
    
# They should even share 
# named variables. 





In [ ]:
function unify!(s,x::Term,y::Term)
    x.head != y.head && fail()
    for i,j in zip(x.args, y.args)
        unify!(s,i,j)
    end
end




In [25]:
unify(x,:a)

:a

In [31]:
x = newvar()
y = newvar()
unify(x,y)
unify(y,:a)
canon(x)

:a

Detemrinstic datalog.

foo(a,b,X) :- greg, larry(a).

function foo(x,y,c)
    unify(x,:a)
    unify(y,:c)
    greg()
    larry(:a)
end

function greg()

function foo(
)
end


Determinstic prolog



Proplog
I love this. it is just the search aspects of prolog/datalog with none of the unification issues.

You can do tabling,
bottom up,
semi naive,
other stuff?  magic sets?


In [46]:
#struct Clause
#    head
#    body
#end

#clauses = Dict{:Symbol, Vector{Vector{Symbol}}}()

#goalstack = [:larry,:shirmy]

function establish(clauses,goalstack)
    println(goalstack)
    if length(goalstack) == 0
        return true
    end
    goal = pop!(goalstack)
    if !haskey(clauses,goal)
        return false
    end
    for clause in clauses[goal]
        if establish(clauses, [goalstack ; clause]) 
            return true
        end
    end
    return false
end
clauses = Dict(
    :moe => [[]],
    :larry => [[]],
    :curly => [[:moe, :larry]]
)


establish(clauses , [:curly, :moe])


[:curly, :moe]
Any[:curly]
Any[:moe, :larry]
Any[:moe]
Any[]


true

In [38]:
x = [1, 2, 3]
y = [1, 2, 3]
z = [x ; y]
pop!(x)
z

6-element Array{Int64,1}:
 1
 2
 3
 1
 2
 3

In [62]:
#bottom uip naive

derived = Set()

clauses = [
    :moe => [],
    :larry => [],
    :curly => [:moe, :larry],
    :gary => [:gary],
    :farly => [:cranly]
]

dirty = true
new = Set()
while true
    for (head, body) in clauses
        if body ⊆ derived
            push!(new, head)
        end
    end
    if derived == new
        break
    end
    derived = derived ∪ new
end

derived

Set{Any} with 3 elements:
  :moe
  :larry
  :curly

In [55]:
[1,3] ∪ Set([1,2,3])

3-element Array{Int64,1}:
 1
 3
 2

In [ ]:
#bottom uip

derived = Set()

clauses = [
    :moe => [],
    :larry => [],
    :curly => [:moe, :larry],
    :gary => [:gary],
    :farly => [:cranly]
]

dirty = true
new = Set()
fresh = Set()
while true
    for (head, body) in clauses
        if length(fresh ∩ body) > 0 && body ⊆ derived
            push!(new, head)
        end
    end
    fresh = derived \ new
    derived = derived ∪ new
    if length(fresh) == 0
        break
    end
end

derived

In [64]:
using DataStructures

DisjointSets{Union{Int64, Symbol}}(Dict{Union{Int64, Symbol},Int64}(), Union{Int64, Symbol}[], IntDisjointSets{Int64}(Int64[], Int64[], 0))