Alright Anyons in Julia.


It makes sense.


We have high performance stuff
we have a community
we have easy linear algerba
we have catlab for drawing



I should revisit my notes.


dense vs sparse matrices.

symbolic anyon trees


Quantum physics list
https://docs.google.com/document/d/13i5TCm2-E_352ulXRMcREUKBHxLVGfWvmC4xpwwvF_E/edit



https://github.com/Jutho/TensorOperations.jl

https://github.com/Jutho/TensorKit.jl - interesting


2Hilb Vicary
https://arxiv.org/pdf/1207.4563.pdf

Also Mike Stay and Vicary with 2Rel. https://arxiv.org/abs/1301.3393


matrices of integers = 1morphism
2-morphisms = 


It's not the density matrix
It's a combinatorial formalism
Like how 2Rel was a combinatorial formalism of nondetermism.

Combinatorial ~ Probabilsitc assuming fairness between all possilbilites



measure_x : V2 -> (V2, V2)
measure_x _ -> ( spinup, spindown)

However, if this measurement is entangled with other pieces of the system


Kron V2 V2 -> (V2, V2)


But then arbitrary measurements do get probabilitiesa associated with them


Kron V2 V2 -> [ ( label,  P *  Kron V2 V2 ) ]

classical choice:
label -> label'

classically applied operator
label -> U


measureent
V2 -> [(label , V2)]


composition?
otimes?

[(label, V2)] here the entire hilbert space is taking the place of C
Which is supposed to be the categrofication process, sure.

or 
     (V2, V2)

Hmm. yes. It produces a direct sum
V2 -> DSum V2 V2

So is this thing the 2 morphism? The only stuff with actual numbers in it are the 2 morphisms

scalars are n copies of Hilb
morphissm are matrices of vector spaces.
Index persective = matrix of types using Tuple and Either [  ]



f g h
And natural transformations between?
forall a. g a -> k a are the morpshism,
They can be composed vertically and horizontally.



pulbic vs private infromation, not encoded vs unecndoed

Question 1: How to simulate.

Of course the first natural question is: is such and such protocol secure
Given all public ifomration + private information, can we determine x
Or can we reduce the probability on x.


Tags for public / private
publish converts private into public.



What muight first come into people's heads.
Maintain a public information dictionary
Maintain objects that contain personal info
Objects feel very natural here.

1. Write a monolithic step by step
2. Some class based shit?


https://en.wikipedia.org/wiki/Cryptographic_protocol
https://www.cs.purdue.edu/homes/bendy/cs590-mpl/#Clarkson+HYP hyperproperties. Relational specification


2Rel. isn't so much a category with a layer above it so much as a category with a layer below it.
publish transitions private information to public.





In [ ]:
#2Rel
struct ZeroCell
    set
end

struct OneCell
    dom Set{A}
    cod Set{B}
    Dict{Tuple{A,B}, Set{C} }
end


struct TwoCell 
    Dict{Tuple{A,B},  Array{ Tuple{C,D}  }  }
end


idOne(m) = {  (s,s) => 1 for s in m  } 
composeOne(f,g) = 

type ZeroCell = Set
    Bool : Set
    Unit : Set
type OneCell = A -> B -> Set
    ex1 True False = Bool
    ex1 _ _ = Void
        




In [ ]:
# is life simplified by making finite sets = Int

ZeroSet = Int
OneCell = Matrix{Int}
Rel = Matrix{Bool}
TwoCell = Matrix{  Rel  } # out matrix is t,s. inner matrix is A B

relCompose() = 
# we could cast back to Bool orr just let it ride.
*(x::Rel, y::Rel) = x * y
+(x::Rel, y::Rel) = x .|| y

composeOneCell(f,g) = f * g
horCompose(f,g) = f * g 
#vcompose(f,g) = 


In [7]:
x = [true false; false  true]
#Bool.(x * x)
Bool(0)

false

In [6]:
@macroexpand @enum Fib I τ

:($(Expr(:toplevel, :(#= Enums.jl:184 =#), :(begin
      $(Expr(:meta, :doc))
      primitive type Fib <: Base.Enums.Enum{Int32} 32 end
  end), :(#= Enums.jl:185 =#), :(function Fib(var"#15#x"::Base.Enums.Integer)
      #= Enums.jl:186 =#
      (0 Base.Enums.:<= var"#15#x" Base.Enums.:<= 1) || Base.Enums.enum_argument_error(:Fib, var"#15#x")
      #= Enums.jl:187 =#
      return Base.Enums.bitcast(Fib, Base.Enums.convert(Int32, var"#15#x"))
  end), :(#= Enums.jl:189 =#), :((Base.Enums.Enums).namemap(::Base.Enums.Type{Fib}) = begin
          #= Enums.jl:189 =#
          Dict{Int32,Symbol}(0 => :Id,1 => :Tau)
      end), :(#= Enums.jl:190 =#), :((Base.Enums.Base).typemin(var"#17#x"::Base.Enums.Type{Fib}) = begin
          #= Enums.jl:190 =#
          Fib(0)
      end), :(#= Enums.jl:191 =#), :((Base.Enums.Base).typemax(var"#18#x"::Base.Enums.Type{Fib}) = begin
          #= Enums.jl:191 =#
          Fib(1)
      end), :(#= Enums.jl:192 =#), :(let var"#13#insts" = (Base.Enums.Any[Fib(var"#

In [1]:
 @enum Fib I τ

In [ ]:
# naw screw this. Leafs should just be Fib
#struct Leaf
#    particle::Fib
#end

struct Split
    particle::Fib
    left::Union{Split,Fib}
    right::Union{Split,Fib}
end

#=
Split{T} to generalize

=#


# Put the counts into the shape?
struct TreeShapeNode
    left::Union{TreeShapeNode,Fib}
    right::Union{TreeShapeNode,Fib}
end

struct TreeShapeRoot
    root::Fib
    left::TreeShapeNode
    right::TreeShapeNode
end

    

In [3]:
shape_helper(x::Split) = TreeShapeNode(shape_helper(x.left), shape_helper(x.right))
shape_helper(p::Fib) = x

shape(x::Split) = TreeShapeRoot(x.particle,  shape(x.left), shape(x.right))
shape(p::Fib) = x



shape (generic function with 2 methods)

In [5]:
Dict( Split(τ,τ,τ) => 1im )

Dict{Split,Complex{Int64}} with 1 entry:
  Split(τ, τ, τ) => 0+1im

In [ ]:
struct FibVect10
    shape::SplittingPatternRoot
    data::Dict{Union{Split,Fib}, Complex{Float64}}
end

In [ ]:
function funzo(x,y) = 

In [9]:
?merge

search: merge merge! MergeSort



```
merge(d::AbstractDict, others::AbstractDict...)
```

Construct a merged collection from the given collections. If necessary, the types of the resulting collection will be promoted to accommodate the types of the merged collections. If the same key is present in another collection, the value for that key will be the value it has in the last collection listed.

# Examples

```jldoctest
julia> a = Dict("foo" => 0.0, "bar" => 42.0)
Dict{String,Float64} with 2 entries:
  "bar" => 42.0
  "foo" => 0.0

julia> b = Dict("baz" => 17, "bar" => 4711)
Dict{String,Int64} with 2 entries:
  "bar" => 4711
  "baz" => 17

julia> merge(a, b)
Dict{String,Float64} with 3 entries:
  "bar" => 4711.0
  "baz" => 17.0
  "foo" => 0.0

julia> merge(b, a)
Dict{String,Float64} with 3 entries:
  "bar" => 42.0
  "baz" => 17.0
  "foo" => 0.0
```

---

```
merge(combine, d::AbstractDict, others::AbstractDict...)
```

Construct a merged collection from the given collections. If necessary, the types of the resulting collection will be promoted to accommodate the types of the merged collections. Values with the same key will be combined using the combiner function.

# Examples

```jldoctest
julia> a = Dict("foo" => 0.0, "bar" => 42.0)
Dict{String,Float64} with 2 entries:
  "bar" => 42.0
  "foo" => 0.0

julia> b = Dict("baz" => 17, "bar" => 4711)
Dict{String,Int64} with 2 entries:
  "bar" => 4711
  "baz" => 17

julia> merge(+, a, b)
Dict{String,Float64} with 3 entries:
  "bar" => 4753.0
  "baz" => 17.0
  "foo" => 0.0
```

---

```
merge(a::NamedTuple, bs::NamedTuple...)
```

Construct a new named tuple by merging two or more existing ones, in a left-associative manner. Merging proceeds left-to-right, between pairs of named tuples, and so the order of fields present in both the leftmost and rightmost named tuples take the same position as they are found in the leftmost named tuple. However, values are taken from matching fields in the rightmost named tuple that contains that field. Fields present in only the rightmost named tuple of a pair are appended at the end. A fallback is implemented for when only a single named tuple is supplied, with signature `merge(a::NamedTuple)`.

!!! compat "Julia 1.1"
    Merging 3 or more `NamedTuple` requires at least Julia 1.1.


# Examples

```jldoctest
julia> merge((a=1, b=2, c=3), (b=4, d=5))
(a = 1, b = 4, c = 3, d = 5)
```

```jldoctest
julia> merge((a=1, b=2), (b=3, c=(d=1,)), (c=(d=2,),))
(a = 1, b = 3, c = (d = 2,))
```

---

```
merge(a::NamedTuple, iterable)
```

Interpret an iterable of key-value pairs as a named tuple, and perform a merge.

```jldoctest
julia> merge((a=1, b=2, c=3), [:b=>4, :d=>5])
(a = 1, b = 4, c = 3, d = 5)
```

---

```
 merge(counters...)
```

Creates a new counter with total counts equal to the sum of the counts in the counters given as arguments.

See also merge!

---

```
merge(sc1, sc2...)
```

This returns a SortedDict or SortedMultiDict that results from merging SortedDicts or SortedMultiDicts `sc1`, `sc2`, etc., which all must have the same key-value-ordering types. In the case of keys duplicated among the arguments, the rightmost argument that owns the key gets its value stored for SortedDict. In the case of SortedMultiDict all the key-value pairs are stored, and for keys shared between `sc1` and `sc2` the ordering is left-to-right. This function is not available for SortedSet, but the `union` function (see below) provides equivalent functionality. Time: O(*cN* log *N*), where *N* is the total size of all the arguments.

---

```
merge(sc1, sc2...)
```

This returns a SortedDict or SortedMultiDict that results from merging SortedDicts or SortedMultiDicts `sc1`, `sc2`, etc., which all must have the same key-value-ordering types. In the case of keys duplicated among the arguments, the rightmost argument that owns the key gets its value stored for SortedDict. In the case of SortedMultiDict all the key-value pairs are stored, and for keys shared between `sc1` and `sc2` the ordering is left-to-right. This function is not available for SortedSet, but the `union` function (see below) provides equivalent functionality. Time: O(*cN* log *N*), where *N* is the total size of all the arguments.


In [ ]:
Base.:+(x::FibVect10,y::FibVect10) = FibVect10( x.shape, merge(+,x.data,y.data))
Base.:*(s::Number , x::FibVect10) = FibVect10(x.shape, Dict(x => s * a for (x, a) in x.data))

In [15]:
#map(x -> 8 * x, Dict(:a => 4))
Dict(x => 8 * a for (x, a) in Dict(:a => 4, :x => 7))

Dict{Symbol,Int64} with 2 entries:
  :a => 32
  :x => 56

In [9]:
Split(Id, Leaf(Id), Leaf(Id))



Split(Id, Leaf(Id), Leaf(Id))

In [ ]:
function count(p, t::Split ) 
    if p == Id 
                        return count(Tau, t.left  ) * count(Tau,t.right) + count(Id,t.left) * count(Id, t.right) 
                     else
        return  count(Tau, t.left  ) * count(Tau,t.right) + count(Tau,t.left) * count(Id, t.right) + count(Id,t.left) * count(Tau, t.right) 
                    end
end
count(p, t::Leaf ) = if (p == t.particle) 1 else 0 end

In [13]:
3 Dict(:a => 1.0, :b => 2.0)

LoadError: syntax: invalid identifier name "."

In [23]:
3 * [1 2 3] + [2 3 4]

1×3 Array{Int64,2}:
 5  9  13

In [21]:
v = [1 2 3]
3v

1×3 Array{Int64,2}:
 3  6  9

In [29]:
Dict(Leaf(Tau) => 3, Split(Tau,Tau,Tau) => 4)

MethodError: MethodError: Cannot `convert` an object of type 
  Fib to an object of type 
  Union{Leaf, Split}
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T at essentials.jl:171

https://github.com/JuliaCollections/AbstractTrees.jl  has a pretty printer. That seems nice
https://github.com/JuliaCollections/DataStructures.jl dicitonaries with defaults.



In [4]:
import Pkg; Pkg.add("DataStructures")

   Updating registry at `~/.julia/registries/General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


Fetching: [========================================>]  100.0 %                                ]  15.0 %Fetching: [=======>                                 ]  17.5 %                           ]  32.4 % [===================>                     ]  47.4 %]  62.3 %===============================>         ]  77.3 %92.2 %Fetching: [======================================>  ]  92.6 %Fetching: [======================================>  ]  93.1 %

  Resolving package versions...
Updating `~/.julia/environments/v1.5/Project.toml`
  [864edb3b] + DataStructures v0.17.20
No Changes to `~/.julia/environments/v1.5/Manifest.toml`


In [1]:
using DataStructures

In [14]:
up = DefaultDict(0im,true => 1 + 0im)
down = DefaultDict(0im,false => 1 + 0im)

DefaultDict{Bool,Complex{Int64},Complex{Int64}} with 1 entry:
  false => 1+0im

No map for dict? Bummer.

Default Dict let's us return 0 for non existent entries which is nice.

Overload addition and scalar multiplication

In [11]:
Base.:+(x :: DefaultDict, y :: DefaultDict) = DefaultDict(0,mergewith(+, x, y))
Base.:*(s, x::DefaultDict) = DefaultDict(0, map((kv) -> (kv[1], s*kv[2]), collect(x)))

In [15]:
2down

DefaultDict{Bool,Complex{Int64},Int64} with 1 entry:
  false => 2+0im

In [11]:
[1 2 3] + [4 5 6]

1×3 Array{Int64,2}:
 5  7  9

In [ ]:
|00>D ict( true => 1.0 + 0im, false => 0im  )

In [18]:
length(down)

1

In [22]:
getindex(down, false)

1 + 0im

In [8]:


struct DictVect{K,V} <: AbstractVector{V}
    it::DefaultDict{K,V}
end

DictVect( args... ) = DictVect(DefaultDict(0, args...))
Base.:+(x :: DictVect, y :: DictVect) = DictVect(mergewith(+, x.it, y.it))
Base.map( f, x::DictVect ) = DictVect(map(f, collect(x)))
Base.:*(s, x::DictVect) = map((kv) -> (kv[1], s*kv[2]), x)
#Base.dot( x::DictVect, y.DictVect ) = length(x) < length(y) ?      : 


In [ ]:
# From the julia docs https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-array
# a "toy" sparse array type
julia> struct SparseArray{T,N} <: AbstractArray{T,N}
           data::Dict{NTuple{N,Int}, T}
           dims::NTuple{N,Int}
       end

julia> SparseArray(::Type{T}, dims::Int...) where {T} = SparseArray(T, dims);

julia> SparseArray(::Type{T}, dims::NTuple{N,Int}) where {T,N} = SparseArray{T,N}(Dict{NTuple{N,Int}, T}(), dims);

julia> Base.size(A::SparseArray) = A.dims

julia> Base.similar(A::SparseArray, ::Type{T}, dims::Dims) where {T} = SparseArray(T, dims)

julia> Base.getindex(A::SparseArray{T,N}, I::Vararg{Int,N}) where {T,N} = get(A.data, I, zero(T))

julia> Base.setindex!(A::SparseArray{T,N}, v, I::Vararg{Int,N}) where {T,N} = (A.data[I] = v)

In [7]:
copy(Dict(true => 0))

Dict{Bool,Int64} with 1 entry:
  true => 0

In [11]:
z = DictVect(true => 0) # printing is now done via abstractarrtay interface. interesting.
3

3

In [16]:
allbools = (true, false)


(true, false)

In [ ]:
# eh. Screw this.
function Base.:*(y::DefaultDict, x::DefaultDict)
   map( ycol -> x[ycol[1]]    ,   collect(y))
end

In [ ]:
map( x ->  , x::DictVect)

In [ ]:
σₓ = 

In [ ]:
ann(i) = LinearOperator(v -> DefaultDict( 0 , [  ] ))
cre(j)

sum2( (i,j) ->  H[i,j] * cre(i) ∘ ann(j)) * 