In [3]:
using DataFrames




┌ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
└ @ Base loading.jl:1278


# DataFrame Style Linear Relations

DataFrames is a julia lbirary that is the analog of Pandas for python or related tools in R. They store tabular data, meaing they have columns and rows.
It has proven to be a popular and intuitive interface to store, retrievce and manipulate tabular data.


Databases store finite relations.
A mathematical model of databases is that of a relation.
Conceptually for me every column has a set of possible values that column can take. Maybe it's integers or strings or an finite enum lik :red :green :blue.
The DataFrame is storing a relation. A relation with column sets A,B,C,D is a subset of A\timesB\timesC\timesD. In other words { (a,b,c,d) | a \in A, b\in B, c \in C,   } Each row stores a tuple (a,b,c,d,...).



Similarly a linear relation is describing a subset of 
Each column has is a vector space which may be 0,1,2,3... dimensional.
What makes it a linear relation is that rather than describing an arbitrary subset of this space, it only describes subsets closed under vector addition, i.e linear subspaces.

If we only had to store finite number of discrte points in this space, we could use data frames as is.

DataFrame( A = [1,0] , B = [ 0  1; 0  1] ) describes the two points (1,0,1) (0,0,1) as elements of R^1 \times R^2.

When we print out this dataframe, we can see a matrix.

This is important, because it's impossible to enumeratively store every element of an arbitrary continuous blob, but we can store generators or equations that somehwhat implicitly describe a linear subsapce more more succintly.


 DataFrameG( A = [1,0] , B = [0 1 ; 0 1] ) describes now any linear combinator of the points  v = \lambda_1 (1,0,1) + \lambda_2 (0,0,1), which is equivalent to the xz plane. So we could equaivlaent have written this data frame as DataFrameG( A = [1, 0], B = [0 0 ; 0 1]) no harm done.
 
 
 It is ubiquitous in mathemtatics that we can describe things in a way that builds them up or cuts them away.
 Parametrzied vs implciit surfaces (sin(\theta), cos(\theta) , 0   ) is a paremtrzied circle in the xy plane. Alternaitvely it can be described by the two equations z = 0, x^2 + y^2 + z^2 == 1 as the intersection of the xy plane and a sphere.
 
 Or a sphere can be parametrzied by ( ),  alternaitvely
 
 A 2 dimensional surface needs 2 parameters to build up from 0, or 1 constraint to cut down from 3. A 1 dimensional surface needs 1 parameter to build up or 2 constraints to cut down from 1.
 
 
 
 
 LinFrame
span( {    |   } )



Most database queries are trivially polynomial time in the size of the database. The game is to keep the power of the polynomial low and worry about consdtant factors.


For exmaple, a boolean formula could be considered as described a set of bools for which the formula evluates to true. We could think of this formula being merely a representation of the finite set of all it's satisfying values. 
As considered as a function of the number of columnns (variables) this database is however exponential time to search in the worst case.
For boolean formulas that are not very sparsely satisfiable, to directly store the values would take space expotnential in the number columns. Which then also takes exponential time at least to process in any way.

There are sets that are even worse. Questions about sets can become undecidable, where it is not possible to even guarantee a brute force method to answer to queries.


Let's say we have a database that has a single column of strings. Let's say we want this database to hold all strings that do not have the character 'a' in them. Completely impossible.

So Databases are not capable of holding arbitrary sets, even for finite data types. They as a practical matter can only hold extremely sparse sets.



Very often you want not linear relations, but affine relations. Affine subspaces are linear subspaces but with an offset from the origin. Offsets occurr in circuit from current or voltage sources. 



Categorical Arrays = finite data types


Relation of this to catgeorical style, if you're willing to name your entities.
Span technology
Gaussians


## Joins

## Groupings

## Applying Linear Maps



In [2]:
import Pkg; Pkg.add("DataFrames")

   Updating registry at `~/.julia/registries/General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


Fetching: [========================================>]  99.9 %13.3 %>                             ]  27.5 %                  ]  54.0 % [===========================>             ]  67.3 %]  80.5 %======================================>  ]  93.8 %

  Resolving package versions...
  Installed PooledArrays ────── v0.5.3
  Installed MbedTLS_jll ─────── v2.16.8+1
  Installed StructTypes ─────── v1.1.0
  Installed CategoricalArrays ─ v0.8.3
  Installed DataFrames ──────── v0.21.8
Updating `~/.julia/environments/v1.5/Project.toml`
  [a93c6f00] + DataFrames v0.21.8
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [324d7699] + CategoricalArrays v0.8.3
  [a93c6f00] + DataFrames v0.21.8
  [41ab1584] + InvertedIndices v1.0.0
  [c8ffd9c3] ↑ MbedTLS_jll v2.16.8+0 ⇒ v2.16.8+1
  [2dfb63ee] + PooledArrays v0.5.3
  [856f2bd8] + StructTypes v1.1.0


In [ ]:
# if we gave every variable a name. We could store the 
# adding to the 


# conceptually, the generator framework is closer to standard Dataframes
# If you wanted to represent a nearly full database, you would store the elements not in the relation.


# Equations cut down vector spaces
# Generators build it up

# Dataframes also typically live in an implied inifinite univcerse, which makes things trickier
# They do not store the realsm of possibility. Although they could

df = DataFrame( A = [1 0], B = [1],    )

In [5]:
DataFrame( A = [1.0, 0.0] , B = [[ 0  3.14], [0  2.0]] )

2×2 DataFrame
│ Row │ A       │ B          │
│     │ Float64 │ Array…     │
├─────┼─────────┼────────────┤
│ 1   │ 1.0     │ [0.0 3.14] │
│ 2   │ 0.0     │ [0.0 2.0]  │

In [6]:
struct DataFrameG
    it
end

DataFrameG(; kwargs...) = DataFrameG(DataFrame(;kwargs...))




DataFrameG

In [7]:
DataFrameG( A = [1.0, 0.0] , B = [[ 0  3.14], [0  2.0]] )

DataFrameG(2×2 DataFrame
│ Row │ A       │ B          │
│     │ Float64 │ Array…     │
├─────┼─────────┼────────────┤
│ 1   │ 1.0     │ [0.0 3.14] │
│ 2   │ 0.0     │ [0.0 2.0]  │)

In [10]:
df = DataFrame(A = 1:4, B = ["M", "F", "F", "M"])
df.A
names(df)

2-element Array{String,1}:
 "A"
 "B"

Maybe I could use the raw DataFrame object, but require a new column :Gen, :Rel

A mixed representation might be fine, but only if consistent.


In [18]:
hcat([[ 0;  3.14], [0;  2.0]]... )'

2×2 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 0.0  3.14
 0.0  2.0

In [ ]:


function linearjoin(df, dg; on = cols)
    fcol = names(df)
    gcol = names(dg)
    ins = filter( c -> c ∈ cols , fcol)
    outs = filter( c -> c ∈ cols , gcol)

    A = Matrix(df[:, ins])
    B = Matrix(df[:, cols])
    C = Matrix(dg[:, cols])
    D = Matrix(dg[:, outs])
    
    # extract sizes of different matrices
    (m, n) = size(A)
    (n1, x) = size(B)
    ny, yi = size(C)
    ny1, yo = size(D)

    
    # combine constraints
    constraints = [ A             B   zeros(nx,yo) ;
                    zeros(ny,xi)  C         D     ]
    # convert to range representation
    B = nullspace(A)
    # project in range representation
    projB = [B[1:xi       ,:] ;
             B[xi+yi+1:end,:] ]
    # return to nullspace representation
    C = Base.transpose(nullspace(Base.transpose(projB)))
    
    #rebuild Dataframe
    
    return LinRel( C[:, 1:xi] ,C[:,xi+1:end] )

    
    
    
    A = df[:,Cols(cols)]
    B = df[:,Not(Cols(cols))]
    C = dg[:,Cols(cols)]
    D = dg[:,Not(Cols(cols))]
    
    
    
    
    

end


In [ ]:
# actually we want to overload indexing too.
# hmm.

function getindex(df::DataFrameG, cols)
    

end



In [109]:
using LinearAlgebra

# nullconvert turns span rep to constraint rep or vice cersa
function nullconvert(df)
    cols = names(df)
    A = nullspace(Matrix(df))
    DataFrame(mapslices(x->[x], A, dims=2)[:] , cols ) #https://discourse.julialang.org/t/converting-a-matrix-into-an-array-of-arrays/17038/2
end


spanrep(x) = isspanrep(x) ? x : nullconvert(x)
consrep(x) = isconsrep(x) ? x : nullconvert(x)

# We tag somewhat inelegantly whether we're inb the span rep or constrain rep via a column tag
isspanrep(x) = "spanrep" ∈ names(x)
isconsrep(x) = "consrep" ∈ names(x)


function spanrep(x) 
    if isspanrep(x)
        return x
    else
        df = select(x, Not(:consrep))
        df = nullconvert(df)
        df[:spanrep] = 0 #missing
        return df
    end
end

function consrep(x) 
    if isconsrep(x)
        return x
    else
        df = select(x, Not(:spanrep)) #remove tag
        df = nullconvert(df)
        df[:consrep] = 0 #add tag 
        return df
     end
end
        #=
#vrep(x) = isvrep(x) ? x : nullconvert(x)
#hrep(x) = ishrep(x) ? x : nullconvert(x)

function DataFrameGen( x...; kwargs...)
    df = DataFrame(x...; kwargs...)
    df[:gen] = missing
    df
end

        df = DataFrame( A = [1.0, 0 ,0] , B = [0,0,0], C = [1,0,0])

x = hrep(df)
Matrix(hrep(hrep(x))) ≈ Matrix(x)  # no
x
#hrep(hrep(x))
dg =  DataFrame( A = [1.0, 0 ,0] , B = [0,0,0], D = [1,0,0])
        
        =#
        
function DataFrameSpan( x...; kwargs...)
    df = DataFrame(x...; kwargs...)
    df[:spanrep] = 0 # missing
    df
end

# representing linear relations via constraints
function DataFrameCons( x...; kwargs...)
    df = DataFrame(x...; kwargs...)
    df[:consrep] = 0 # missing
    df
end






function linearjoin(df,dg)  # ; on=[], makefresh=false )
        df = coalesce.(consrep(df), 0)
        dg = coalesce.(consrep(dg), 0)
         coalesce.(vcat(df,dg, cols=:union), 0)
end


function linearproject(df, cols)
        df = spanrep(df)
        df = df[ [cols ; :spanrep]]
end

df = DataFrameCons( A = [1.0, 0 ,0] , B = [0,0,0], C = [1,0,0])
dg = DataFrameCons( A = [1.0, 0 ,0] , E = [0,0,0], C = [1,0,0])
isconsrep(df)
#"consrep" ∈ names(df)
spanrep(linearjoin(df,dg))

# linearproject( df, cols )

#innerjoin( df,dg)

resistor(R, i , v1, v2) = DataFrameCons( [i => [R], v1 => [1], v2 => [-1] ] )
vsource(V, v1, v2) =  DataFrameCons( [:one => [V], v1 => [1], v2 => [-1] ] )
isource(I, i) =  DataFrameCons( [:one => [I], i => [-1] ] )

r1 = resistor(10, :i1, :v1, :v2)
r2 = resistor(10, :i1, :v2, :v3)


sys = consrep(linearproject(linearjoin(r1,r2), [:i1, :v1, :v3]) )  #[:, [:i1,:v1,:v3]]
print(sys)
#print(sys[:, [:v1,:v3] ] ./ sys.i1

# a cross join might give something weird. Some kind of kron product?

function compose(df,dg) 
    inner_names = names(df) ∩ names(dg)
    dh = linearjoin(df,dg)
    linearproject(dg, inner_names)
end

1×4 DataFrame
│ Row │ i1       │ v1        │ v3         │ consrep │
│     │ Float64  │ Float64   │ Float64    │ Int64   │
├─────┼──────────┼───────────┼────────────┼─────────┤
│ 1   │ 0.997509 │ 0.0498755 │ -0.0498755 │ 0       │

compose (generic function with 1 method)

In [63]:
df.gen = missing

missing

3×4 DataFrame
│ Row │ A       │ B     │ C     │ gen     │
│     │ Float64 │ Int64 │ Int64 │ Missing │
├─────┼─────────┼───────┼───────┼─────────┤
│ 1   │ 1.0     │ 0     │ 1     │ missing │
│ 2   │ 0.0     │ 0     │ 0     │ missing │
│ 3   │ 0.0     │ 0     │ 0     │ missing │

In [31]:
df = DataFrame( A = [1.0, 0.0] , B = [[ 0  3.14], [0  2.0]] )

hcat(Array(df)...)
Array(df)

2×2 Array{Array{Float64,N} where N,2}:
 [1.0]  [0.0 3.14]
 [0.0]  [0.0 2.0]

In [33]:
df = DataFrame( A = [1.0, 0.0] , B = [3.14, 2.0] )
Matrix(df)




2×2 Array{Float64,2}:
 1.0  3.14
 0.0  2.0