maybe I should do a shitty grobner basis algo, Just cause it might be useful to have access to guts.


Operads grobner https://www.maths.tcd.ie/~vdots/AlgebraicOperadsAnAlgorithmicCompanion.pdf What the heck. From Evan's site

Archived:
https://github.com/tkluck/FGb.jl



Also, could finally try to understand knuth bendix

What is the general procedure:

determine a monomial ordering


we want an ordered thing by leading term.


https://www.researchgate.net/publication/220460160_An_Introduction_to_Knuth-Bendix_Completion



It seems like sorted containers might be useful.

I feel like i don't have very satisfying data structures, but I should ignore that probably
http://www.cs.tau.ac.il/~nachumd/course.html


http://haskellformaths.blogspot.com/2010/05/string-rewriting-and-knuth-bendix.html nice post. a relatively straightforward presentation?


https://www.sciencedirect.com/science/article/pii/S0747717199902626 - categorical completion algorithm 

It's kind of constructively build a term that could go two ways. Then add the two ways to your set of rules. rinse ancd repeat

https://cstheory.stackexchange.com/questions/12326/unification-and-gaussian-elimination
completion algorithms


I guess grobner wise, we build a polynomial that could've gone two ways The the least common multiple monomial?). and then the S polynomial is the result of long devision by either choice.  

Term rewriting
String rewriting
Word problems


the group axioms


For catgeoyr theor rewriting
Hash cons / sharing
oldest/shortest mix (or someother metric besides shortest)

Polynomials with a monomial ordering can be thgouth of as the equation / rewrite rule

lt(p) -> p - lt(p)


linear equations + a basis ordering
Gaussian elmination can be thought of as reorgniazation
lt(v) -> v - lt(v)
this is the triangular solve.



There is a procedure ("unification") which finds ways of matching patterns to each other.
This produces a set of all the possible subpieces where one could apply rule A vs rule B and where it might matter.
Apply A and B to this matched object. Then reduce it with all the known rules so far.

For grobner basis, this common object is the monomial that is the least common multiple of the leading monomials of the individuals.
Then reduction of this lcm monomial with respect to poly 1 vs poly2 builds the S-polynomial once oirented. Again the "rewrite" can be though of as two sides of an equation, or putting everything on one side as subtraction.

For linear equations, the 

for strings the least common multiple is an overlapping configuration
Semi-thue systems



Resolution / Superposition? 
Superpsoition of one term over the other.

What is the pattern and rewrite of a cnf clause? Maybe clause -> True?
Or negatiion -> positive. Rewrite in terms of implications?
There isn't an obvious term ordering really?
The entire clause is the monomial here? Just a term member of the clause?

Graver basis?

There is a possible matching stage


x^m 


https://github.com/HarrisonGrodin/Completion.jl


https://www.meetup.com/papers-we-love/events/242063907/ bazerman talk on term rewriting via homology
http://math.ucr.edu/home/baez/week70.html
https://www.youtube.com/watch?v=WdawrT-6Qzk

evan also had topological looking rewriting links on his page?


https://homepage.divms.uiowa.edu/~fleck/181content/taste-fixed.pdf


http://www.scholarpedia.org/article/Buchberger%27s_algorithm

https://doc.sagemath.org/html/en/reference/polynomial_rings/sage/rings/polynomial/toy_buchberger.html




the f4 algorithm
abuses sparse linear algebra to do s polynomial reduction in parallel

You can pack nonlinear problems into linear problems by sort of brute force expadning the multiplications.
You'll find thias of this character in resolvents, the sylvester matrix

For example suppose I made a vector where every row correpsonds to a monomial. Addidng these vectors corresponds to adding polynomials.
I can make a matrix that acts on this vector that correspond to multiplying by another polynomial p. All I need to do is fill each column of the matrix with waht polynomial would result from 

https://github.com/gcalderone/ReusePatterns.jl @forward macro that may be useful for orderings of polynomials

https://ir.lib.uwo.ca/cgi/viewcontent.cgi?article=7762&context=etd high performance sparse polynimials thesis




In [10]:
length("113241")

6

In [11]:
for c in "21312"
    print(c)
end

21312

In [14]:
"s213123"[1:4] == 

"s213"

In [21]:
"21312"[5:end]

"2"

I probably shouldn't mash these toghether.

There's no reason, since I need to splice them different too.
Is there no way to do this elegantly? I guess boundaries are always shit


Do i want a sorted dict for reduction.
Do I do repeat the largest reductions first? Can I guarantee smaller reductions won't unlock the large one? Or is that part of the point?


Reduction

So I guess that lhs that are directly reducible from each other?


Everything is secrelty equations.

If you reduce a rhs, that's fine
but reducing a lhs you may have to consider reorienting the rule, or that it has become a pure equality




In [ ]:
using 



In [63]:
for (k,v) in Dict(:a => 2)
    print(k)
end

a

In [64]:
function reduce_match( p , m)
    old = nothing
    new = p
    while old != new
        old = new
        for (l,r) in m
            new = replace(new, l => r)
        end
    end
    return new
end
            


reduce_match (generic function with 1 method)

In [ ]:

# SKI calculus.
# needs regexp groups. But would regexp be able to handle nested parentehsis properly?
Dict( "" => ,  )

In [71]:
!true

false

In [ ]:
processed = Dict()
unprocessed = orig


while !empty(unprocessed)
    for s2 in processed
        for l,r in critialpair()
            if l < r
                unprocessed.add(r => l)
            elseif r < l
                unprocessed.add(l => r)
            end
        end
    end
end



compress?





In [69]:
reduce_match("ababababababababa", Dict("ababa" => "abc", "bc" => "a"))

"aabaabaa"

In [56]:
function overlaps(s1::String,s2::String) # it actually isn't necessary they're strings. Any iterable of somethign with equality.
    if length(s1) < length(s2) # make s1 the bigger string or equal
        tmp = s1
        s1 = s2
        s2 = s1
    end
    n1 = length(s1)
    n2 = length(s2)
    return Iterators.flatten((
                   [i-n2+1 for i in 1:n2 if s1[1:i] == s2[n2-i+1:end]  ],
                   [ i for i in 2:(n1-n2) if s1[i:i+n2-1] == s2 ], #not very ends
            [n1 - i + 1 for i in 1:n2 if s1[n1-i+1:end] == s2[1:i]  ]))
end

overlaps (generic function with 2 methods)

In [57]:
s1 = "abab"
s2 = "ab"
n1 = length(s1)
n2 = length(s2)
[n1 - i + 1 for i in 1:n2 if s1[n1-i+1:end] == s2[1:i]  ]
#[i-n2+1 for i in 1:n2 if s1[1:i] == s2[n2-i+1:end]  ]
#[ i for i in 2:(n1-n2) if s1[i:i+n2-1] == s2 ]

1-element Array{Int64,1}:
 3

In [58]:
s1[1:1+2]

"aba"

In [60]:
collect(overlaps("abababab", "ab"))

4-element Array{Int64,1}:
 1
 3
 5
 7

In [62]:
collect(overlaps("cabababab", "abc"))

2-element Array{Int64,1}:
 -1
  8

In [1]:
replace("abab", "ab" => "c")

"cc"

In [4]:
split("abcab", "ab") # what about partial overlaps? Could double the rule?


3-element Array{SubString{String},1}:
 ""
 "c"
 ""

In [6]:
match(r"abcab", "ab")

In [7]:
match(r"ab", "abcab")

RegexMatch("ab")

In [8]:
eachmatch(r"ab", "abcab")

Base.RegexMatchIterator(r"ab", "abcab", false)

In [ ]:
function critical(l1 => r1, l2 => r2 )
    = split(l1,l2)

end

In [2]:
using DataStructures
# https://juliacollections.github.io/DataStructures.jl/v0.9/sorted_containers.html

In [3]:
SortedDict("ab" => "c", "a" => "b")

SortedDict{String,String,Base.Order.ForwardOrdering} with 2 entries:
  "a"  => "b"
  "ab" => "c"

In [ ]:
Set{Array{T}} # represent a linear subspace as a set of vectors
# term ordering


l
lt
lc
reduce( a , Set )
reduce( a , b )


In [ ]:



Set{( Array{Symbol}  ,  Array{Symbol} )}




In [ ]:
function replace(x,lhs,rhs)
    for i in 1:(len(x) - n)
        if s[i:i+n] == lhs
            return concatenate( x[1:i] , rhs , x[i+n:end] ) 
        end
    end
end


function reduce(x, s)
    done = false
    while done == false
        done = true
        for (lhs,rhs) in s
            res = replace(x,lhs,rhs)
            if res != nothing
                x = res
                done = false
            end
        end
    end
end



In [ ]:
Set([1 0 2], [2 4 0])

for v,w in s
    i = lm(v) # index of first non zero
    j = lm(w) # index of first non zero
    if j < i
        

# long division by a vector is triangular solving

In [4]:
using DynamicPolynomials

┌ Info: Precompiling DynamicPolynomials [7c1d4256-1411-5781-91ec-d7bc3513ac07]
└ @ Base loading.jl:1260


In [9]:
@polyvar x y

(x, y)

In [6]:
dump(x)

PolyVar{true}
  id: Int64 253
  name: String "x"


In [21]:
dump(x*x)

Monomial{true}
  vars: Array{PolyVar{true}}((1,))
    1: PolyVar{true}
      id: Int64 254
      name: String "x"
  z: Array{Int64}((1,)) [2]


In [22]:
dump(3*x*x)

Term{true,Int64}
  α: Int64 3
  x: Monomial{true}
    vars: Array{PolyVar{true}}((1,))
      1: PolyVar{true}
        id: Int64 254
        name: String "x"
    z: Array{Int64}((1,)) [2]


In [10]:
dump(x * y + 1.4)

Polynomial{true,Float64}
  a: Array{Float64}((2,)) [1.0, 1.4]
  x: MonomialVector{true}
    vars: Array{PolyVar{true}}((2,))
      1: PolyVar{true}
        id: Int64 254
        name: String "x"
      2: PolyVar{true}
        id: Int64 255
        name: String "y"
    Z: Array{Array{Int64,1}}((2,))
      1: Array{Int64}((2,)) [1, 1]
      2: Array{Int64}((2,)) [0, 0]


In [ ]:
function sortpoly!(p) # actually we hsould dispatch sort
    o = sortperm(p.Z)
    p.a = p.a[o]
    p.x.Z = p.x.Z[o]    
end

In [40]:
typeof(x*x*y + 1)

Polynomial{true,Int64}

In [32]:
function lm(p) # leading monomial
        return Monomial(p.x.vars , p.x.Z[1]) # should return a term
end 
    

lm (generic function with 1 method)

In [33]:
function lt(p)
    return Term(p.a[1], lm(p))
end

lt (generic function with 1 method)

In [47]:
4x*x*x >= 3x*x*x

true

In [52]:
divrem(x*x*x , x)

(x², 0.0)

In [57]:
divrem(7x*x*y+1, x*y)

(7.0x, 1.0)

In [55]:
methods(divrem)

# 11 methods for generic function "divrem":
[1] divrem(x::BigInt, y::BigInt) in Base.GMP at gmp.jl:560
[2] divrem(x::Union{Int128, Int16, Int32, Int64, Int8}, y::Unsigned) in Base at int.jl:177
[3] divrem(x::Unsigned, y::Union{Int128, Int16, Int32, Int64, Int8}) in Base at int.jl:182
[4] divrem(x::Integer, y::Integer, rnd::RoundingMode{:Nearest}) in Base at div.jl:131
[5] divrem(x::Integer, y::Integer, rnd::RoundingMode{:NearestTiesAway}) in Base at div.jl:147
[6] divrem(x::Integer, y::Integer, rnd::RoundingMode{:NearestTiesUp}) in Base at div.jl:163
[7] divrem(a::T, b::Base.MultiplicativeInverses.MultiplicativeInverse{T}) where T in Base.MultiplicativeInverses at multinverses.jl:152
[8] divrem(f::AbstractPolynomialLike{T}, g::AbstractPolynomialLike{S}; kwargs...) where {T, S} in MultivariatePolynomials at /home/philip/.julia/packages/MultivariatePolynomials/fixWm/src/division.jl:35
[9] divrem(f::AbstractPolynomialLike{T}, g::AbstractArray{#s15,1} where #s15<:AbstractPolynomialLike{S}; kwargs...) where {T, S} in MultivariatePolynomials at /home/philip/.julia/packages/MultivariatePolynomials/fixWm/src/division.jl:61
[10] divrem(x, y) in Base at div.jl:118
[11] divrem(a, b, r::RoundingMode) in Base at div.jl:120

In [38]:
lt(x*x + 3y * y * y + 1) / lt( X * X + 1)

UndefVarError: UndefVarError: X not defined

In [ ]:
function Base.divrem(x::Polynomial{true,T}, d::Polynomial{true,Int64})
    r = x
    ltr = lt(r)
    ltd = lt(d)
    while ltr >= ltd
        
end

In [ ]:
#from poly.jl
# Invariant:
# a and x might be empty: meaning it is the zero polynomial
# a does not contain any zeros
# x is increasing in the monomial order (i.e. grlex)

In [ ]:
function divy(x, d) # order
    #sortpoly!(x)
    #sortpoly!(d)
    r = x
    ltr = lt(r)
    ltd = lt(d)
    while ltr >= ltd
        m = ltr / ltd
        y += m*d
        r -= m * d
    end
    return y,r 

    
end

function divmod(p::Var,q::Var)
function divmod(p::Monomial,q::Monomial)
function divmod(p::Term,q::Term)
function divmod(p::Polynomial,q::Polynomial)
    


function spoly(p,q)
    
end


function reduce(p, rs) # rs should be sorted.
    for r in rs
        _, p = divy(p,r)
    end
end

function selfreduce(rs)
    for i in 1:length(rs)
        r = rs[i]
        reduce()
    end
    
    while nonempty(rs)
        r = rs.pop()
        r = reduce(r,rs)
        if !iszero(r)
            r2.push(r)
        end
    end
end

function grobner(ps)
    rs = []
    r2s = ps
    while nonempty(r2s)
        rs += r2s
        for i,p in enumerate(rs)
            for q in rs[i:end]
                s = spoly(p,r)
                s = reduce(s, rs)
                if !nonzero(s)
                    r2s.push(s)
                end
            end
        end
        # selfreduce?
    end
    return rs
end







In [62]:
x*x + 1 <= 7 + x

MethodError: MethodError: no method matching isless(::Polynomial{true,Int64}, ::Polynomial{true,Int64})
Closest candidates are:
  isless(!Matched::Missing, ::Any) at missing.jl:87
  isless(::Any, !Matched::Missing) at missing.jl:88

In [67]:
((x, y) -> x )(1,2)

1

In [70]:
?enumerate

search: enumerate



```
enumerate(iter)
```

An iterator that yields `(i, x)` where `i` is a counter starting at 1, and `x` is the `i`th value from the given iterator. It's useful when you need not only the values `x` over which you are iterating, but also the number of iterations so far. Note that `i` may not be valid for indexing `iter`; it's also possible that `x != iter[i]`, if `iter` has indices that do not start at 1. See the `pairs(IndexLinear(), iter)` method if you want to ensure that `i` is an index.

# Examples

```jldoctest
julia> a = ["a", "b", "c"];

julia> for (index, value) in enumerate(a)
           println("$index $value")
       end
1 a
2 b
3 c
```


In [72]:
for (i,j) in enumerate(5:10)
    print(i)
end

123456

In [115]:
?sort

search: sort sort! sortperm sortperm! sortslices sortmonovec Cshort issorted



```
sort(v; alg::Algorithm=defalg(v), lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Variant of [`sort!`](@ref) that returns a sorted copy of `v` leaving `v` itself unmodified.

# Examples

```jldoctest
julia> v = [3, 1, 2];

julia> sort(v)
3-element Array{Int64,1}:
 1
 2
 3

julia> v
3-element Array{Int64,1}:
 3
 1
 2
```

---

```
sort(A; dims::Integer, alg::Algorithm=DEFAULT_UNSTABLE, lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Sort a multidimensional array `A` along the given dimension. See [`sort!`](@ref) for a description of possible keyword arguments.

To sort slices of an array, refer to [`sortslices`](@ref).

# Examples

```jldoctest
julia> A = [4 3; 1 2]
2×2 Array{Int64,2}:
 4  3
 1  2

julia> sort(A, dims = 1)
2×2 Array{Int64,2}:
 1  2
 4  3

julia> sort(A, dims = 2)
2×2 Array{Int64,2}:
 3  4
 1  2
```


In [77]:
iszero(x - x)

true

In [95]:
lcm(x*x*x, y*x*x)

x³y

In [98]:
div(x*x*x, x)

x²

In [125]:
dump(3x - 3x)

Polynomial{true,Int64}
  a: Array{Int64}((0,)) Int64[]
  x: MonomialVector{true}
    vars: Array{PolyVar{true}}((1,))
      1: PolyVar{true}
        id: Int64 254
        name: String "x"
    Z: Array{Array{Int64,1}}((0,))


In [129]:
?leadingmonomial

search: leadingmonomial



```
leadingmonomial(p::AbstractPolynomialLike)
```

Returns the monomial of the leading term of `p`, i.e. `monomial(leadingterm(p))` or `first(monomials(p))`.

### Examples

Calling `leadingmonomial` on $4x^2y + xy + 2x$ should return $x^2y$.


In [148]:
using MultivariatePolynomials

ArgumentError: ArgumentError: Package MultivariatePolynomials not found in current path:
- Run `import Pkg; Pkg.add("MultivariatePolynomials")` to install the MultivariatePolynomials package.


In [150]:
DynamicPolynomials.MP

MultivariatePolynomials

In [ ]:
prcoessed = []
unprocessed = []

# when something moves from unprocesed to processed, it puts all the spoly with the prcoessed into unprocessed.


In [41]:
using DynamicPolynomials
using DataStructures
@polyvar x y

#function lm(p::Polynomial{true,T}) where {T} # leading monomial
#    return iszero(p) ? constantmonomial(p) : Monomial(p.x.vars , p.x.Z[1])
#end 


#function lm(p::Term{true,T}) # leading monomial
#    return p.x
#end 

#function polyreduce(p, rs) # rs should be sorted.
#    rs = sort(rs, rev=true, lt = (x, y) -> leadingmonomial(x) <= leadingmonomial(y))
#    for r in rs
#        if iszero(p)
#            return p
#        end
#        if !iszero(r)
#           _, p = divrem(p,r)
#        end
#    end
#    return p
#end

function spoly(p,q)
    pq = lcm(leadingmonomial(p),leadingmonomial(q))
    return div(  pq , leadingterm(p) ) * p - div(pq , leadingterm(q)) * q
end


#function buchberger(F::Array{Polynomial{true,T}}) where {T <: Number}
function buchberger(F::AsbstractPolynomialLike) where {T <: Number}
pairs = Queue{Tuple{Polynomial{true,T}, Polynomial{true,T}}}()
    for (i, f1) in enumerate(F)
        for f2 in F[i+1:end]
            enqueue!(pairs, (f1,f2))
        end
    end
    
    while !isempty(pairs)
        println(pairs)
        println(F)
        (f1,f2) = dequeue!(pairs)
        s = spoly(f1,f2)
        _,s = divrem(s,F) #polyreduce(s, F)
        println(s)
        if !iszero(s) #isapproxzero?
            for f in F
                enqueue!(pairs, (s,f))
            end
            push!(F,s)
        end
    end
    println("reduce")
    G = Array{Polynomial{true,T}}(undef, 0) #[]
    while !isempty(F)
        f = pop!(F)
        _,r = divrem(f, vcat(F,G))
        if !iszero(r)
            push!(G,r)
        end
    end
    #for (i, f) in enumerate(F)
    #   print(F)
    #    if i == 1
    #       _,F[i] = divrem(f, F[2:end])
    #    elseif i > 1 & i < length(F)
    #        _,F[i] = divrem(f, vcat(F[1:i-1], F[i+1:end]))
    #    elseif i == length(F)
    #        _,F[i] = divrem(f, F[1:end-1])
    #    end
    #end
    
    return G #filter(x -> !iszero(x) , F)
end

buchberger (generic function with 2 methods)

In [5]:
using DynamicPolynomials
using MultivariatePolynomials
using DataStructures
@polyvar x y

function spoly(p,q)
    pq = lcm(leadingmonomial(p),leadingmonomial(q))
    return div(  pq , leadingterm(p) ) * p - div(pq , leadingterm(q)) * q
end

function isgrobner(F::Array{T}) where {T <: AbstractPolynomialLike} # check buchberger criterion
    for (i, f1) in enumerate(F)
        for f2 in F[i+1:end]
            s = spoly(f1,f2)
            _,s = divrem(s,F)
            if !iszero(s)
                return false
            end
        end
    end
    return true
end

function buchberger(F::Array{T}) where {T <: AbstractPolynomialLike}
    pairs = Queue{Tuple{T,T}}()
    # intialize with all pairs from F
    for (i, f1) in enumerate(F)
        for f2 in F[i+1:end]
            enqueue!(pairs, (f1,f2))
        end
    end
    
    # consider all possible s-polynomials
    while !isempty(pairs)
        (f1,f2) = dequeue!(pairs)
        s = spoly(f1,f2)
        _,s = divrem(s,F)
        if !iszero(s) #isapproxzero?
            for f in F
                enqueue!(pairs, (s,f))
            end
            push!(F,s)
        end
    end

    # reduce redundant entries in grobner basis.
    G = Array{T}(undef, 0)
    while !isempty(F)
        f = pop!(F)
        _,r = divrem(f, vcat(F,G))
        if !iszero(r)
            push!(G,r)
        end
    end
    
    return G
end

buchberger (generic function with 1 method)

MethodError: MethodError: no method matching isless(::Polynomial{true,Int64}, ::Polynomial{true,Int64})
Closest candidates are:
  isless(!Matched::Missing, ::Any) at missing.jl:87
  isless(::Any, !Matched::Missing) at missing.jl:88

In [29]:
methods(buchberger)

# 6 methods for generic function "buchberger":
[1] buchberger(F::AbstractPolynomialLike{T}) where T<:Number in Main at In[1]:34
[2] buchberger(F::Array{AbstractPolynomial{T},N} where N) where T<:Number in Main at In[5]:34
[3] buchberger(F::Array{AbstractPolynomial,N} where N) in Main at In[18]:35
[4] buchberger(F::Array{AbstractPolynomialLike{T},N} where N) where T<:Number in Main at In[3]:34
[5] buchberger(F::Array{AbstractPolynomialLike,N} where N) in Main at In[21]:35
[6] buchberger(F::Array{T,N} where N) where T<:AbstractPolynomialLike in Main at In[28]:35

In [8]:
isgrobner(buchberger( [ x + 1.0 + y   , 2.0x + 3y + 7  ] ))

true

In [15]:
buchberger( [ x + 1.0 + y   , 2.0x + 3y + 7  ] )

2-element Array{Polynomial{true,Float64},1}:
 -0.5y - 2.5
 x - 4.0

In [2]:
buchberger([x , y])

Queue{Tuple{PolyVar{true},PolyVar{true}}}(Deque [Tuple{PolyVar{true},PolyVar{true}}[(x, y)]])
PolyVar{true}[x, y]
0.0
reduce


2-element Array{PolyVar{true},1}:
 y
 x

In [18]:
res = buchberger( [ x^3 - y , x^2 - x*y ])
isgrobner(res)

true

In [36]:
isempty([])

true

In [32]:
divrem(x+1, )

MethodError: MethodError: no method matching div(::Polynomial{true,Int64}, ::Array{Any,1}, ::RoundingMode{:ToZero})
Closest candidates are:
  div(::Any, ::Any) at div.jl:37
  div(!Matched::Bool, !Matched::Bool, ::RoundingMode{:ToZero}) at div.jl:219
  div(!Matched::Bool, !Matched::Bool, ::RoundingMode) at div.jl:216
  ...

In [43]:
divrem(x^1+1, x^1 - x^1)
typeof([ x + 1.0 + y   , 2.0x + 3y + 7  ])

Array{Polynomial{true,Float64},1}

In [12]:
spoly( x + 1.0 + y   , 2.0x + 3y + 7  )

-0.5y - 2.5

In [10]:
p =   x + 1.0 + y 
q = 2.0x + 3y + 7
pm = leadingmonomial(p)
    qm = leadingmonomial(q)
    pq = lcm(pm,qm)
    div(  pq , leadingterm(p) ) * p - div(pq , leadingterm(q)) * q
#print(div(pq,qm))

-0.5y - 2.5

In [54]:
[ 1 1 ; 2  3 ] \ [-1 ; -7]

2-element Array{Float64,1}:
  4.0
 -5.0

In [16]:
typeof([ x^3 - y , x^2 - x ])

Array{Polynomial{true,Int64},1}

In [19]:
p =    x^3 - y 
q = x^2 - x
pm = leadingmonomial(p)
    qm = leadingmonomial(q)
    pq = lcm(pm,qm)
    div(  pq , leadingterm(p) ) * p - div(pq , leadingterm(q)) * q
#print(pq)

x² - y

In [20]:
polyreduce(x^2 - y, [ x^3 - y , x^2 - x ])

x - y

In [28]:
polyreduce(polyreduce(spoly(x-y, x^3 - y ), [   x^3 - y , x^2 - x  , x - y]), [   x^3 - y , x^2 - x  , x - y])

-y² + y

In [29]:
polyreduce(polyreduce(spoly(x-y,  x^2 - x ), [   x^3 - y , x^2 - x  , x - y]), [   x^3 - y , x^2 - x  , x - y])

-y² + y

In [11]:
spoly(x-y,  -y^2 + y )

-y³ + xy

In [19]:
rs =[   x^3 - y , x^2 - x  , x - y, -y^2-y]
rs = sort(rs, rev=true, lt = (x, y) -> leadingmonomial(x) <= leadingmonomial(y))

4-element Array{Polynomial{true,Int64},1}:
 x³ - y
 x² - x
 -y² - y
 x - y

In [22]:
divrem(spoly(x-y,  -y^2 + y ), -y^2 - y)
divrem(x*y - y, x - y)

(y, y² - y)

In [14]:
polyreduce(polyreduce(polyreduce(spoly(x-y,  -y^2 + y ), [   x^3 - y , x^2 - x  , x - y, -y^2-y]),[   x^3 - y , x^2 - x  , x - y, -y^2-y]), [   x^3 - y , x^2 - x  , x - y, -y^2-y])

-2.0y

In [7]:
p = -y^2 + y
q = -y^2 + y
    pq = lcm(leadingmonomial(p),leadingmonomial(q))
   !iszero( div(  pq , leadingterm(p) ) * p - div(pq , leadingterm(q)) * q)


false

In [46]:
polyreduce(x^3 - y, res)

Polynomial{true,Int64}[y² - y, x - y]y^2 - y
x^3 - y
x^3 - y
Polynomial{true,Float64}
  a: Array{Float64}((2,)) [1.0, -1.0]
  x: MonomialVector{true}
    vars: Array{PolyVar{true}}((2,))
      1: PolyVar{true}
        id: Int64 271
        name: String "x"
      2: PolyVar{true}
        id: Int64 272
        name: String "y"
    Z: Array{Array{Int64,1}}((2,))
      1: Array{Int64}((2,)) [3, 0]
      2: Array{Int64}((2,)) [0, 1]
x - y
x^3 - y
y^3 - y
Polynomial{true,Float64}
  a: Array{Float64}((2,)) [1.0, -1.0]
  x: MonomialVector{true}
    vars: Array{PolyVar{true}}((2,))
      1: PolyVar{true}
        id: Int64 271
        name: String "x"
      2: PolyVar{true}
        id: Int64 272
        name: String "y"
    Z: Array{Array{Int64,1}}((2,))
      1: Array{Int64}((2,)) [0, 3]
      2: Array{Int64}((2,)) [0, 1]


y³ - y

In [49]:
x <= y^2

true

In [32]:
divrem(x^3 - y, res[1])
divrem(y^3 - y, res[2])

(y + 1.0, 0.0)

In [89]:
push!([2x + 7],2x + 7)

2-element Array{Polynomial{true,Int64},1}:
 2x + 7
 2x + 7

In [82]:
[1 2 3 ][4]

BoundsError: BoundsError: attempt to access 1×3 Array{Int64,2} at index [4]

def buchberger(F, reduced=True):
    """Toy implementation of Buchberger algorithm. """
    G, pairs = list(F), set([])

    for i, f1 in enumerate(F):
        for f2 in F[i+1:]:
            pairs.add((f1, f2))

    while pairs:
        f1, f2 = pairs.popitem()

        s = s_polynomial(f1, f2)
        _, h = reduced(s, G)

        if h != 0:
            for g in G:
                pairs.add((g, h))

            G.append(g)

    if reduced:
        for i, g in enumerate(G):
            _, G[i] = reduced(g, G[:i] + G[i+1:])

        G = map(monic, G)

    return G
    
 https://mattpap.github.io/masters-thesis/html/src/groebner.html
 
 https://scicomp.stackexchange.com/questions/21699/benchmarks-for-gr%c3%b6bner-bases-and-polynomial-system-solution
 
 https://mathoverflow.net/questions/322518/computing-groebner-basis-for-a-complicated-systems-of-polynomials

In [16]:
sortperm( [ [3,4] ,[1,1] , [4,5,6]   ])

3-element Array{Int64,1}:
 2
 1
 3

In [17]:
methods(sort)

# 8 methods for generic function "sort":
[1] sort(r::AbstractUnitRange) in Base at range.jl:969
[2] sort(r::AbstractRange) in Base at range.jl:972
[3] sort(x::SparseArrays.SparseVector{Tv,Ti}; kws...) where {Tv, Ti} in SparseArrays at /home/philip/Downloads/julia-1.4.1/share/julia/stdlib/v1.4/SparseArrays/src/sparsevector.jl:1914
[4] sort(v::AbstractArray{T,1} where T; kws...) in Base.Sort at sort.jl:763
[5] sort(A::AbstractArray; dims, alg, lt, by, rev, order) in Base.Sort at sort.jl:1028
[6] sort(d::OrderedCollections.OrderedDict; args...) in OrderedCollections at /home/philip/.julia/packages/OrderedCollections/b4td4/src/dict_sorting.jl:20
[7] sort(d::Dict; args...) in OrderedCollections at deprecated.jl:65
[8] sort(d::OrderedCollections.LittleDict; byvalue, args...) in OrderedCollections at /home/philip/.julia/packages/OrderedCollections/b4td4/src/dict_sorting.jl:24

In [15]:
?sortperm

search: sortperm sortperm! partialsortperm partialsortperm! isconcretetype



```
sortperm(v; alg::Algorithm=DEFAULT_UNSTABLE, lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Return a permutation vector `I` that puts `v[I]` in sorted order. The order is specified using the same keywords as [`sort!`](@ref). The permutation is guaranteed to be stable even if the sorting algorithm is unstable, meaning that indices of equal elements appear in ascending order.

See also [`sortperm!`](@ref).

# Examples

```jldoctest
julia> v = [3, 1, 2];

julia> p = sortperm(v)
3-element Array{Int64,1}:
 2
 3
 1

julia> v[p]
3-element Array{Int64,1}:
 1
 2
 3
```
