
# Computational group theory

Sims book
Handbook
Permutations kos Seress, "Permutation group algorithms

https://www.math.colostate.edu/~hulpke/CGT/cgtnotes2up.pdf

https://en.wikipedia.org/wiki/Computational_group_theory

Rubiks cube


GAP

knuth bendix string

homotopy groups?

sim schreier https://en.wikipedia.org/wiki/Schreier%E2%80%93Sims_algorithm
a sequence of subgroups akin to the echlon form of a matrix, which is a sequence of subspaces.




sympy actually has a decent number of algorithms



meataxe


normal subgroup has same left and right cosets. Requirement of making a quotient group


wreath product - in sims books, it was an interesting way of producting orders on strings?
semidirect product



# orbit
If we're given the group saying its generated by these r generaating moves on a permutation of a set, that doesn't mean we can answer everything about the group.
A rubiks cube is permutations of it's faces. But actually only those made by twists.







# coset enumeration
todd-coxeter https://en.wikipedia.org/wiki/Todd%E2%80%93Coxeter_algorithm

So we start with a subgroup. Who know how you find that. By inspection?

|G| = |G : H|  |H|. lagranges theorem

cosert enumeration as equality saturation.
`H = <x x^2>`
x 

The index is the size of |G : H| number of cosest https://en.wikipedia.org/wiki/Index_of_a_subgroup


huh. It really is like an egraph

H = <words  >
H may not be finite (?) and we may not know how to normalize it

h1 h2 h3 h4 = x(y(z(id)))

relations: become eqsat rules.  x(x(Z)) -> Z

left and right multiplication are akin somehow to the two choices of cons list reps of sequences?





# Graphs
Graphs and automorphisms
isomorphisms

orbits and stabilizers

nauty

refinement. Like number of edges and labels as colors breaks it up that uatomorphisms have to be a subgroup of a direct product of permutations inside colors.
It always was a subgroup of permutations of all vertices.


symmettry breaking



#  Representation theory

meataxe
representation theory https://en.wikipedia.org/wiki/Representation_theory



I have a draft somewhere about "big dumb ape"

https://en.wikipedia.org/wiki/Representation_theory_of_finite_groups
finbite groups gram somethjing
characters
schur's lemma. https://en.wikipedia.org/wiki/Schur%27s_lemma
That group theory for physicisists book
https://en.wikipedia.org/wiki/Maschke%27s_theorem
irreducible representyations https://en.wikipedia.org/wiki/Irreducible_representation


https://en.wikipedia.org/wiki/Selection_rule

clebsch gordon https://en.wikipedia.org/wiki/Clebsch%E2%80%93Gordan_coefficients
wigner  https://en.wikipedia.org/wiki/3-j_symbol

wigner eckart https://en.wikipedia.org/wiki/Wigner%E2%80%93Eckart_theorem

```python
import handcalcs.render

```


```python
import numpy as np
import scipy as sp
import scipy.linalg
sigx = np.array([[0, 1], [1, 0]])
sigy = np.array([[0, -1j], [1j, 0]])
sigz = np.array([[1, 0], [0, -1]])


H = np.hstack((sigx, sigy, sigz))
sp.linalg.svd(H)
L = sigx**2 + sigy**2 + sigz**2
print(sp.linalg.eig(L))


sigx2 = np.kron(sigx, sigx)
sigy2 = np.kron(sigy, sigy)
sigz2 = np.kron(sigz, sigz)
H = np.hstack((sigx2, sigy2, sigz2))
sp.linalg.svd(H)
L = sigx2**2 + sigy2**2 + sigz2**2
sp.linalg.eig(L)
```

    (array([1.+0.j, 1.+0.j]), array([[1.+0.j, 0.+0.j],
           [0.+0.j, 1.+0.j]]))





    (array([ 3.+0.j, -1.+0.j,  3.+0.j, -1.+0.j]),
     array([[ 0.70710678+0.j, -0.70710678-0.j, -0.        -0.j,
             -0.        -0.j],
            [-0.        -0.j, -0.        -0.j,  0.70710678-0.j,
              0.70710678+0.j],
            [-0.        -0.j, -0.        -0.j,  0.70710678+0.j,
             -0.70710678-0.j],
            [ 0.70710678-0.j,  0.70710678+0.j, -0.        -0.j,
             -0.        -0.j]]))



# Tao challeange

forall x y, m(m(x, x), y) = m(y, x)      ==>    forall x y, m(x, y) = m(y, x)

https://terrytao.wordpress.com/2024/09/25/a-pilot-project-in-universal-algebra-to-explore-new-ways-to-collaborate-and-use-machine-assistance/

https://mathstodon.xyz/@tao/110736805384878353

https://mathoverflow.net/questions/450890/is-there-an-identity-between-the-commutative-identity-and-the-constant-identity/450905#450905

https://github.com/teorth/equational_theories

In [9]:
T = smt.DeclareSort("T")
dir(T)

['__bool__',
 '__class__',
 '__copy__',
 '__deepcopy__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rshift__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_repr_html_',
 'as_ast',
 'ast',
 'cast',
 'ctx',
 'ctx_ref',
 'eq',
 'get_id',
 'hash',
 'kind',
 'name',
 'sexpr',
 'subsort',
 'translate',
 'use_pp']

In [1]:
import kdrag as kd
import kdrag.solvers as solvers
import kdrag.smt as smt

T = smt.DeclareSort("T")
x,y,z = smt.Consts("x y z", T)
mul = smt.Function("mul", T, T, T)
kd.notation.mul.define([x,y], mul(x,y))

s = solvers.VampireSolver()
s.add(smt.ForAll([x,y,z], (x * x) * y == y * x))
s.add(smt.Not(smt.ForAll([x,y], x * y == y * x)))
s.set("timeout", 1000)
print(s.check())
print(s.res.stdout.decode())



unsat
WARNING Broken Constraint: if inline_let(on) has been set then newcnf(off) is equal to on
WARNING Broken Constraint: if inline_let(on) has been set then newcnf(off) is equal to on
WARNING Broken Constraint: if inner_rewriting(on) has been set then saturation_algorithm(fmb) is equal to lrs or saturation_algorithm(fmb) is equal to otter or saturation_algorithm(fmb) is equal to discount
WARNING Broken Constraint: if inline_let(on) has been set then newcnf(off) is equal to on
WARNING Broken Constraint: if symbol_precedence(reverse_arity) has been set then saturation_algorithm(fmb) is equal to lrs or saturation_algorithm(fmb) is equal to otter or saturation_algorithm(fmb) is equal to discount
WARNING Broken Constraint: if sos(all) has been set then saturation_algorithm(fmb) is equal to lrs or saturation_algorithm(fmb) is equal to otter or saturation_algorithm(fmb) is equal to discount
WARNING Broken Constraint: if literal_maximality_aftercheck(on) has been set then saturation_algorith

In [16]:
I = smt.IntSort()
I2 = smt.DeclareSort("Int")
I.get_id() == I2.get_id()
I2.kind()
I.kind()
I.name() == I2.name()
dir(I2)

['__bool__',
 '__class__',
 '__copy__',
 '__deepcopy__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rshift__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_repr_html_',
 'as_ast',
 'ast',
 'cast',
 'ctx',
 'ctx_ref',
 'eq',
 'get_id',
 'hash',
 'kind',
 'name',
 'sexpr',
 'subsort',
 'translate',
 'use_pp']



# Knucklegroup

the Identity Problem for Semigroups
https://arxiv.org/pdf/2302.05939

https://github.com/Z3Prover/z3/discussions/7332

 "formulas(assumptions).
 (xy)z=x(yz).
 x1x2=(((x1x1)*x1)*x1)x2.
 ((((((x1x2)*x1)*x2)*x1)*x2)*x1)x2=(((x1x2)*x2)*x2)x2.
 ((x1x2)*x3)x4=(((((x1x2)*x1)*x1)*x1)*x3)x4.
 end_of_list.

 formulas(goals).
 ((((c1c1)*c2)*c2)*c1)c2=((((c1c1)*c2)*c1)*c2)*c2.
 end_of_list.

GAP could probably handle this.
Twee


In [11]:
from  dataclasses import dataclass
import kdrag as kd
import kdrag.smt as smt
@dataclass(frozen=True)
class Group():
    T : smt.SortRef
    e : smt.ExprRef
    mul : smt.FuncDeclRef
    inv : smt.FuncDeclRef
    mul_assoc : kd.kernel.Proof
    left_unit : kd.kernel.Proof
    left_inv : kd.kernel.Proof
    def __post_init__(self):
        T, mul, inv, e = self.T, self.mul, self.inv, self.e
        assert mul.arity() == 2 and inv.arity() == 1
        assert mul.domain(0) == T and mul.domain(1) == T and self.mul.range() == self.T
        assert inv.domain(0) == T and inv.range() == T
        x,y,z = [smt.FreshConst(self.T, prefix=x) for x in "x y z".split()]
        kd.lemma(kd.QForAll([x,y,z], mul(mul(x,y),z) == mul(x,mul(y,z))), by=[self.mul_assoc])
        kd.lemma(kd.QForAll([x], mul(e,x) == x), by=[self.left_unit])
        kd.lemma(kd.QForAll([x], mul(inv(x),x) == e), by=[self.left_inv])

UGroupSort = smt.DeclareSort('G') # Uninterpreted Group
e = smt.Const('e', UGroupSort)
x,y,z = smt.Consts('x y z', UGroupSort)                
mul = smt.Function('mul', UGroupSort, UGroupSort, UGroupSort)
kd.notation.mul.register(UGroupSort, mul)
mul_assoc = kd.axiom(kd.QForAll([x,y,z], (x * y) * z == x * (y * z)))
inv = smt.Function('inv', UGroupSort, UGroupSort)
left_unit = kd.axiom(kd.QForAll([x], e * x == x))
left_inv = kd.axiom(kd.QForAll([x], inv(x) * x == e))
UGroup = Group(UGroupSort, e, mul, inv, mul_assoc, left_unit, left_inv)
x,y,z = smt.Reals('x y z')
Group(kd.R, 
      e=smt.RealVal(0), 
      mul=(x+y).decl(), 
      inv=(-x).decl(), 
      mul_assoc=kd.lemma(smt.BoolVal(True)), 
      left_unit=kd.lemma(smt.BoolVal(True)),
      left_inv=kd.lemma(smt.BoolVal(True))) 

Group(T=Real, e=0, mul=+, inv=-, mul_assoc=|- True, left_unit=|- True, left_inv=|- True)

In [ ]:
assert mul.sort() == T >> (T >> T)
assert inv.sort() == T >> T

Ok, but dataclass is kind of wroking against us.

Lawful vs Unlawful split. Hmm.



In [ ]:
from  dataclasses import dataclass
import kdrag as kd
import kdrag.smt as smt
@dataclass(frozen=True)
class Group():
    T : smt.SortRef
    e : smt.ExprRef
    mul : smt.FuncDeclRef
    inv : smt.FuncDeclRef

class LawfulGroup(Group):
    mul_assoc : kd.kernel.Proof
    left_unit : kd.kernel.Proof
    left_inv : kd.kernel.Proof
    def __post_init__(self):
        

In [ ]:
from  dataclasses import dataclass
import kdrag as kd
import kdrag.smt as smt

class Group():
    def __init__(self, T : smt.SortRef,e : smt.ExprRef, mul : smt.ExprRef, inv : smt.FuncDeclRef,by=[]):
        assert mul.arity() == 2 and inv.arity() == 1
        assert mul.domain(0) == T and mul.domain(1) == T and self.mul.range() == self.T
        assert inv.domain(0) == T and inv.range() == T
        self.T = T
        self.e = e
        self.mul = mul
        self.inv = inv
        x,y,z = [smt.FreshConst(self.T, prefix=x) for x in "x y z".split()]
        self.mul_assoc = kd.lemma(kd.QForAll([x,y,z], mul(mul(x,y),z) == mul(x,mul(y,z))), by=by)
        self.left_unit = kd.lemma(kd.QForAll([x], mul(e,x) == x), by=by)
        self.left_inv = kd.lemma(kd.QForAll([x], mul(inv(x),x) == e), by=by)


In [3]:
from z3 import *

G = DeclareSort('G')
mul = Function("mul", G, G, G)
x1,x2,x3,x4 = Consts('x1 x2 x3 x4', G)
x,y,z = Consts('x y z', G)
s = Solver()
ExprRef.__mul__ = lambda x,y: mul(x,y)
s.add(ForAll([x,y,z], mul(x,mul(y,z)) == mul(mul(x,y),z)))
s.add(x1  * x2 == x1 * x1 * x1 *x1 * x2)
s.add(x1 * x2 * x1 * x2 * x1 * x2 * x1 * x2 == x1 * x2 * x2 * x2 * x2)
s.add(x1 * x2 * x3 * x4 == x1 * x2 *x1 *x1 *x1 *x3 * x4)

s.add(Not(x1 * x1 * x2 * x2 * x1 *x2 == x1 * x1 *x2 *x1 * x2 * x2))
s.check()


All groups of order 2 are commutative

In [2]:
from z3 import *

G = DeclareSort('G')
mul = Function("mul", G, G, G)
inv = Function("inv", G, G)
e = Const('e', G)
x1,x2,x3,x4 = Consts('x1 x2 x3 x4', G)
x, y = Consts('x y', G)
s = Solver()
ExprRef.__mul__ = lambda x,y: mul(x,y)
s.add(ForAll([x1,x2,x3], mul(x1,mul(x2,x3)) == mul(mul(x1,x2),x3)))
s.add(ForAll([x], mul(x,inv(x)) == e))
s.add(ForAll([x], mul(x,x) == e))
s.add(ForAll([x], mul(e,x) == x))
s.add(Not(ForAll([x,y], mul(x,y) == mul(y,x))))
s.check()


unsat



A universe of groups to work in. Abstract G and permutations between. Cayley's theorem.
Or use int -> int functions

In [8]:
from z3 import *
import knuckledragger as kd
import knuckledragger.notation as notation
IFun = ArraySort(IntSort(), IntSort())
x,y,z = Consts("x y z", IFun)
n,m = Ints("n m")
notation.mul.register(IFun, lambda f,g: Lambda([n], f[g[x]]))
inv = Function("inv", IFun, IFun)
e = kd.define("e", [], Lambda([n], n))
#inv_def = kd.axiom(ForAll([n,m,x], Implies(x[n] == m, inv(x)[m] == n)))
#inv(x)[x[n]] <= n
perm = kd.define("perm", [x], x * inv(x) == e)
# perm = Exists([y], x * y == e). Then inv skolemizes. Interesting.
# This is the same pattern as invertible, differentiable, continuous, limit. diffble(f, diff(f))
# diffable = Eixts([g], lim( ) == g)
# diffable = ForAll([g], diff(f) == )
# skolem vs herbrad. Hmm. posdiffable negdiffable.  

#kd.lemma(ForAll([x], perm(x) == (inv(x) * x == e)), by=[])

# homormophism between g1 and g2.
# homo(k,g1,g2) == g1(x) & g1(y) => g2(k(x)) & k(x * y) == k(x) * k(y) & k(inv(x)) == inv(k(x))
# homo(k) == dom(k)? Can I define dom(k)?




AttributeError: 'ArraySortRef' object has no attribute 'is_int'

In [1]:
from z3 import *
def lemma(thm, by=[], admit=False):
    if admit:
        print("  Admitted.", thm)
    else:
        prove(Implies(And(by), thm))
    return thm
B = BoolSort()
BoolRef.__and__ = lambda self, other: And(self, other)

- Subgroup
- Quotient Group
- Lagrange's theorem
- Homomorphisms https://en.wikipedia.org/wiki/Group_homomorphism
- isomorphism theorems https://en.wikipedia.org/wiki/Isomorphism_theorems
- Particular groups - permutations?


Dummit and foote
visual group theory
rotman
aluffi chaptter 0




In [ ]:
G = DeclareSort("G")
mul = Function("mul", G, G, G)
inv = Function("inv", G, G)
ExprRef.__mul__ = lambda self, other: mul(self, other)
e = Const("e", G)

x,y,z = Consts("x y z", G)

g_assoc = ForAll([x, y, z], (x * y) * z == x * (y * z))
g_right_id = ForAll([x], x * e == x)
g_right_inv = ForAll([x], x * inv(x) == e)






In [ ]:
GSet = ArraySort(G, BoolSort())
H,K = Consts("H K", GSet)
subgroup = Function("subgroup", GSet, B)
subgroup_def = ForAll([H], subgroup(H) == ForAll([x, y], Implies(H[x] & H[y], 
                                                                 H[inv(x)] & H[x * y])))

left_coset = Function("left_coset", GSet, GSet)
left_coset_def = ForAll([H], coset(H) == Lambda([x], Exists([y,z], H[y] & x == y * z )))


Universal algebra

finite group
{
    "mul": {(i,j) : (i + j) % 4  for i in range(4) for j in range(4)}
    "inv": {i: 4 - i for i in range(4)}
    "id": 0
}

categorical style
{
    {("mul", (i,j)) : (i + j) % 4  for i in range(4) for j in range(4)}
    + {("inv",i): 4 - i for i in range(4)}
     + {("id",) : 0}
}

falgebra in finset

The initial one isn't in finset though.
quotient group := items are the sets of equivalent members.



