https://lobste.rs/s/l0l4xq/trees_j_wiki 




A Modular Static Cost Analysis For GPU Warp-Level Parallelism
 Gregory Blike, Hannah Zicarelli, Udaya Sathiyamoorthy, Julien Lange, Tiago Cogumbreiro
 

https://pytorch.org/blog/helion/
https://github.com/Riphiphip/mlir_rvsdg
https://discourse.llvm.org/t/mlir-for-rvsdg/471


MLIR

Refinement type system

`SeqSort(Int) -> Real` But with refinement types.
Reshaping scheduling operations as transformations on this.


python sexp frontend into xdsl?

https://arxiv.org/abs/1912.13451  Introduction to Rank-polymorphic Programming in Remora (Draft)

https://github.com/remora-lang/interpreter


Dialegg - where are dialegg's rules?
eqsat



"scheduling"
Large and small scale


smtlib macros

(a -> b) -> c
(int -> int) -> Real  (a sequuence of integer. Tail of sequence is ignored?)

melior 
jlm rvsdg dialect. What makes rvsdg different from mlir itself?


gradual typing




10/23
robert has an ast and interpreter that is canonical
talk to vadym
Colton's thing is nice.
layout using z3 zeke?


https://rschenck.com/docs/phd-thesis.pdf schenk thesis

https://docs.kidger.site/jaxtyping/
https://github.com/agronholm/typeguard
https://github.com/beartype/beartype
chertih - tidal descritpon language



C++ driver of remora. ffi
scheduler cpu vs gpu

getting models from other performers


remora and futhark mlir dialects
How to emit mlir from haskell






The POPL 2025 paper "TensorRight: Automated Verification of Tensor Graph Rewrites",
https://dl.acm.org/doi/10.1145/3704865
seems relevant.

https://charithmendis.com/
https://www.youtube.com/watch?v=wiwloa0g02g thesis defense 2020

https://sites.google.com/illinois.edu/cs521-sp25-mlcompilers/

I just listened to Charith Mendis give an impressive overview of his research, and the two papers he most mentioned were the POPL 25 one and a MICRO 2025 paper, "TAIDL: Tensor Accelerator ISA Definition Language with Auto-generation of Scalable Test Oracles"
https://dl.acm.org/doi/10.1145/3725843.3756075
The title is pretty descriptive: TAIDL is an accelerator-centric DSL for specifying ISA semantics at a high level and also the memory model. They seem to use XLA-HLO, which is another acronym with which I am unfamiliar.
Has anyone read (and understood) the POPL 25 paper?



https://dl.acm.org/doi/pdf/10.1145/3736112.3736141 Star dominic orchard.
Use subtyping and named structred axes. Sum and products. Functor vectors. Direct sum direct product. Named dimensions. Padding inference in addition to broadcasting.

A <= B considered as sets. + meta casting? 


remora lean interpreter?



remora 2.0
compilation via futhark
cps. k-CFA
refinement type for remora


should I just hang out in northeasterns office?

array and size types
map : 'a 'b [n] : (a -> b) -> [n] a -> [n] b



emit mlir from smtlib? Is there gc?



def row_softmax (xs : []f32) : []f32 = 
    let max_x = refuce f32.max f32.lowest xs
    let sum_e = reduce (+) 0 exps
    in map (\e -> e / sum_e) exps

def softamx_matrix (m : [][]f32) : [][]f32 = 
    in map row_softmax e

def dotprod [n] (x : [n]  f64) (y : [n] f64) = 
    f644.sum (map2 (*) x y)

def matmul [n][m][p] : 

(i-app (t-app reduce))


heat
minimization of eignvunfction
fluid sim
nbody

simd/mimd analysis
records. letrec

higher order to first order monomoprhic
monomorphic, no shape and type params


convolution

Int -> Real
SeqInt -> Real
BitVec -> Real


convoluition2d : 
(pi 
 (n Dim)
 (pi (k {s : Shape | (= rank s) (rank n)}))
)

Ignore the Int -> Reral data?
Just think about shape.
Hmmm.

https://prl.khoury.northeastern.edu/blog/2017/05/04/rank-polymorphism/
https://ccs.neu.edu/~jrslepak/Dissertation.pdf

What about polyhedral rank polymorphism
Star - other kinds of inference.

What if tensor knuth bendix was made shape polymorphic? a(i,j,...). Hmm. Or we allowed word equations in there


# ATL

https://dl.acm.org/doi/10.1145/3656390 A Verified Compiler for a Functional Tensor Language

box operator is like a lambda

tensor(start, end, f) produces a tensor.
sum(start,end, f)

Particular combinations are recognized as storable?


inductive Tensor
    | Tensor : Nat -> Nat -> (Nat -> Tensor)
    | Scalar : Real



Dependent types
b ::= Int


Constants 
{v : B | P}

z in Z
------
Gam |- z : {v | v = b}


Make a hass lattice with proofs. Do type inference usning model. Optimization?
iteratively try to get biggest in lattice.
Full Empty

index : l : list A -> {v | 0 <= v <= len(v)} -> A

convolution  list n A -> list m A | m < n -> list (m - n) A

conv  : Pi (img : Dim) Pi (k : Dim d <= img>)  [t ing] -> [t k] -> [t ?]

append : Pi (d : Dim | d <= 5

U>)


use acl2 as a command line tool?

python interface into acl2




# polyhedral dependnecy

forall m <= i <=  n

a(e1) = a(e2)
     = e3


m <= i2 <= i2 <= n
e1(i1) = e2(i2)  then there is a set of dependency edges between 

{(a, e2, a, e1)}

The iteration space doesn't feel like it matters much unless there is observable output inside the loop

for ir = 0 to 100:

[]



https://en.wikipedia.org/wiki/Banerjee_test 
https://en.wikipedia.org/wiki/GCD_test
https://en.wikipedia.org/wiki/Loop_dependence_analysis
https://en.wikipedia.org/wiki/Polytope_model


events 
(a, read, loc, (iter, pc, lhs))
(a, write, (iter, pc, rhs))
(a, loc, (iter, pc, write))
iter indices, pc, and read/write as a timestamp. PC = iter, stmt#, read/write

a purel;y functional expressions can't have the same arrays as both read and write
(a, loc) <- ()

IF you have concrete loop bounds, you can just run it and record read and write events
One could even imagine doing this fast.


In [4]:
# a[i] = a[i-2]
[(ir, iw) for ir in range(5) for iw in range(5) if iw <= ir and iw == ir - 2]

[(2, 0), (3, 1), (4, 2)]

# delinearization
https://www.cs.colostate.edu/~pouchet/doc/ics-article.15a.pdf Optimistic Delinearization of Parametrically Sized Arrays

https://llvm.org/devmtg/2018-04/slides/Absar-ScalarEvolution.pdf SCEV
https://www.npopov.com/2023/10/03/LLVM-Scalar-evolution.html


https://arxiv.org/html/2502.03402v2 tesnro chain of recurrences

"chain of recurrences" https://bohr.wlu.ca/ezima/papers/ISSAC94_p242-bachmann.pdf
Hmm a rewrite rule system. Kind of looks like a fold / reduce. But specialize to particular allowed accumulator expressions. Also maybe the recurrence inter

https://www2.math.upenn.edu/~wilf/AeqB.html

https://arxiv.org/abs/2405.06972 A Machine Learning-based Approach for Solving Recurrence Relations and its use in Cost Analysis of Logic Programs


https://www.cs.fsu.edu/files/reports/TR-041201.pdf  Array Data Dependence Testing with the Chains of Recurrences Algebra∗

https://www.reddit.com/r/Compilers/comments/16z4d57/llvm_scalar_evolution_scev/
"I invented them in the early 2000s based on the Chains of Recurrences algebra, but the method I came up with uses the inverse CR algebra rules that I wrote. I also proved that the CR algebra is complete (sound and terminating), therefore it is normalizing, an important property that other methods for induction variable analysis lack. My graduate student J. Birch later helped to expand the implementation and testing.

I never understood why it was necessary for my fellow academics to rename my method to SCEV. The name is misleading. It is both a representation and an algebra with an inverse transformation.

Some of my papers on Google Scholar:

Van Engelen, Robert A. "Efficient symbolic analysis for optimizing compilers." International Conference on Compiler Construction. Berlin, Heidelberg: Springer Berlin Heidelberg, 2001.

Van Engelen, Robert A., et al. "A unified framework for nonlinear dependence testing and symbolic analysis." Proceedings of the 18th annual international conference on Supercomputing. 2004.

Birch J, van Engelen RA, Gallivan KA, Shou Y. An empirical evaluation of chains of recurrences for array dependence testing. InProceedings of the 15th international conference on Parallel Architectures and Compilation Techniques 2006 Sep 16 (pp. 295-304)."


In [ ]:
% when can we add two shapes?
add(S,S,S).
add([-1 | S], T, K) :- add(S,T,K).







In [ ]:
type Shape = tuple[int, ...]
def good_shape(s1,s2,res):
    frame, cell
def prefix(s1,s2): ...
def frame_cell(s1, c): ...




In [ ]:
from kdrag.all import *

Shape = smt.SeqSort(smt.IntSort())

# predicate for can convert s1 rto s2
#is_reshape = kd.define([s1,s2])
s,s1,s2 = smt.Consts("s s1 s2", Shape)
# a set of shapes. A refinement type?
Type = smt.SetSort(Shape)
rank = kd.define("rank", [s], smt.Length(s))

undef = smt.Const("undef", Shape)
# but there is auto reranking.
kd.notation.add.define([s1,s2], smt.If(s1 == s2, s1, undef))




# F2
https://arxiv.org/pdf/2505.23819 Linear Layouts: Robust Code Generation of Efficient Tensor Computation Using F2
https://link.springer.com/article/10.1007/s11786-025-00602-8



Linear layouts robuts code generation using F2
triton

lyout mpping from logical to logical indexes
offset -> (i,j,k)
dstributed layout (reg,thread,wrp) -> (i,j,...)
if f were linear we could reason about it using linear lagerba

in triton all layouts are powers of 2
2^r regs / thread
2^t threads/warp

smt over finite fields. Hmmm. cvc5 finite fields. 
Grobner bases generalize linear alg. Useful? Claim of pprt 

[1 0 1] = reg 1 thread 3

A = ident = 

well defined search space for layouts
check simd compatbailiy
convert between two layouts.

optimal swizzle layouts
simd read from successive locations

M : offset -> ijk
A : Reg,Th,Wro -> ijk
M^-1 

unimodular matrices for loop interchanges
[
    Ir 0
    0  X  
]  makes register increment match offset layout


two layouts A B
A^-1 B  is harware move

B^-1 A   crreodpons to warp is Iw then doens't chante warp
warp shuffles
vs gpu global memory


other finite fields?

affine

sparse

mlir has triton dialects
gpu and something.
Yikes

cryptominisat?


Haskell.....
.....
....
Ok.












In [ ]:
import cvc5.pythonic as cvc5

cvc5

In [ ]:
import cvc5

FiniteField

from_np()


# remora

is (array [] 17) the same as (array [1] 17)

https://github.com/remora-lang/remora-interpreter-racket

In [16]:
! raco pkg install git://github.com/jrslepak/Remora.git/?path=remora

Querying Git references for remora at git://github.com/jrslepak/Remora.git/?path=remora
raco setup: version: 8.17
raco setup: platform: x86_64-linux [cs]
raco setup: target machine: ta6le
raco setup: installation name: 8.17
raco setup: variants: cs
raco setup: main collects: /usr/racket/collects/
raco setup: collects paths: 
raco setup:   /home/philip/snap/code/209/.local/share/racket/8.17/collects
raco setup:   /usr/racket/collects/
raco setup: main pkgs: /usr/racket/share/pkgs
raco setup: pkgs paths: 
raco setup:   /usr/racket/share/pkgs
raco setup:   /home/philip/snap/code/209/.local/share/racket/8.17/pkgs
raco setup: links files: 
raco setup:   /usr/racket/share/links.rktd
raco setup:   /home/philip/snap/code/209/.local/share/racket/8.17/links.rktd
raco setup: main docs: /usr/racket/doc
raco setup: --- updating info-domain tables ---                    [12:36:04]
raco setup: updating: /home/philip/snap/code/209/.local/share/racket/8.17/share/info-cache.rktd
raco setup: --- pre-inst

In [69]:
%%file /tmp/remoraex.rkt
#lang remora/dynamic
; https://github.com/remora-lang/remora-interpreter-racket/blob/master/remora/scribblings/tutorial.scrbl
;(show 'foo))
(alit (2 3) 7 1 2 2 0 5)
(array 1 2 3 4)
((fn ((x 2)) (+ x 1)) (alit (2 3) 7 1 2 2 0 5))
#A(4)(1 2 3 4)
[(+ 10 3) (+ 20 3) (+ 30 3)]
([+ + +] [10 20 30] [3 3 3])
(+ [10 20 30] [3 3 3]) ; same thing
#r(1 1)+ ; reranking
([magnitude angle] 3+4i)
;(iota [[2 3] [4 2]])
(define (diff-square (x 0) (y 0))
    (- (* x x)
    (* y y)))
(diff-square 5 3)

Overwriting /tmp/remoraex.rkt


In [70]:
! racket /tmp/remoraex.rkt

[[7 1 2]
 [2 0 5]]
[1 2 3 4]
[[8 2 3]
 [3 1 6]]
[1 2 3 4]
[13 23 33]
[13 23 33]
[13 23 33]
#<rem-proc>
[5 0.9272952180016122]
16


In [ ]:
! racket

https://github.com/remora-lang/remora/tree/main/examples
https://github.com/remora-lang/remora-interpreter-racket/tree/master/remora/examples

In [ ]:
from kdrag.all import *

Shape = smt.SeqSort(smt.IntSort())
s1,s2 = smt.Consts("s1 s2", Shape)

s = smt.Solver()
n = smt.Int("n")
#s.add(smt.ForAll([n], smt.Contains(s1, smt.Unit(n)), n >= 0))
#s.add(smt.ForAll([n], smt.Contains(s2, smt.Unit(n)), n >= 0))

s.add(smt.SuffixOf(s1, s2)) # suffix of is basically broadcast compatible, minus the special case for 1
s.add(s1 != smt.Empty(Shape))
s.add(s1 != s2)
s.check()
s.model()

s3 = smt.SeqMap(smt.Lambda([n], smt.Abs(n)), s1) # intrinsically positive.
s3

seq.map(Lambda(n, If(n > 0, n, -n)), s1)

In [ ]:
import numpy as np
import operator
operator.neg(np.array([1]))
np.array([operator.neg])(np.array([1]))
np.ndarray.__call__ = lambda self, *args: 

def call(f, *args):
    

class RArray(list):
    


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
np.zeros(2).reshape((1,2,-1))
np.zeros(2).reshape((-1,2,1))
import numpy as np
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b
vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4], 2)

(np.zeros(2).reshape((1,2,1)) + np.zeros(2).reshape((2,1,1))).shape
np.broadcast_shapes((1, 2), (3, 1), (3, 2), (2,)) # prepend with ones


(3, 2)

In [ ]:
kd.define("broadcast_shapes", [s1,s2], 

# string solving
https://youtu.be/MLwZrU6dOwE?si=TuKdKXKCj65xsYXS https://icetcs.github.io/frocos-itp-tableaux25/slides/tblfro/tableaux7-eisenhofer.pdf https://doi.org/10.1007/978-3-032-06085-3_7 On Solving String Equations via Powers and Parikh Images
https://icetcs.github.io/frocos-itp-tableaux25/recordings.html 

"
- Automatons (z3-noodler, Ostrich, Sloth, TRAU, . . . )
- SAT (Woorpje, nfa2sat)
- Unwinding/model repair (z3, cvc5, S3, z3Str3, . . . )
- Nielsen transformation (more or less in all solvers)
Termination only on “common-fragments”
quadratic, 2-variable, straight-line, chain-free
"

Nielson - from free grou thoery. Non temrimating in general https://en.wikipedia.org/wiki/Nielsen_transformation . Combinatorial group theory. 
parikh ~ character count. Can show some eqwuations can't be solved

Even if nielson happens inside, I could do it outseide.



word constraints
string constraints

word equations https://en.wikipedia.org/wiki/Word_equation
https://en.wikipedia.org/wiki/Combinatorics_on_words

https://drops.dagstuhl.de/storage/00lipics/lipics-vol152-csl2020/LIPIcs.CSL.2020.3/LIPIcs.CSL.2020.3.pdf solving word equatioms by recompressions 2020
also works on traces (partially commutative monoids?)
bubble sort for canonization.

https://github.com/remora-lang/remora/blob/main/src/Symbolic.hs#L65-L88

https://github.com/jrslepak/makanin-algo


https://homepage.divms.uiowa.edu/~ajreynol/pres-tpss2021.pdf cvc5 presentation summary of string solvers

https://assets.amazon.science/be/e6/c0265a14477ca4558784008404ea/solving-string-constraints-using-sat.pdf solving strings using sat 2023 aws

z3-noodler

cvc5

ostrich2

libmata


necklaces and rings.
cycle rewriting. zantema https://arxiv.org/abs/1609.07065 Termination of Cycle Rewriting by Transformation and Matrix Interpretation
https://cofault.com/aodt.html#aodt
Bag(Ring(x)) = e^Ring(x) = List(x) = 1/(1-x)
https://en.wikipedia.org/wiki/Monoid_factorisation#Chen%E2%80%93Fox%E2%80%93Lyndon_theorem   Chen–Fox–Lyndon theorem
Lyndon decomposition of monoid
https://en.wikipedia.org/wiki/Lyndon_word
A necklace as something else in the list, set, multiset hierarchy. You can't really associated


```
au = bv
------
⊥

au = ε
------
⊥

wu = wv
------
u = v

xu = ε
-------
(xu = ε)[x/ε]

xu = av
------
(xu = av)[x/ε] (xu = av)[x/ax′]

xu = yv
------
(xu = yv)[x/y] (xu = yv)[x/yx′] (xu = yv)[y/xy′]
```

https://www.ccs.neu.edu/home/pete/pub/fmcad-2021.pdf Mathematical Programming Modulo Strings. Pete 2021

In [47]:
from dataclasses import dataclass
from typing import NamedTuple

class Var(NamedTuple):
    name : str

def subst(xs : list[object | Var], n : Var, s):
    res = []
    for x in xs:
        if n == x:
            res.extend(s)
        else:
            res.append(x)
    return res

counter = 0
def freshvar():
    global counter
    counter += 1
    return Var(f"_{counter}")


def subst_pair(pair : tuple[list[object | Var], list[object | Var]], n : Var, s):
    x,y = pair
    return (subst(x, n, s), subst(y, n, s))
from collections import deque

def nielson(x : list[object | Var], y : list[object | Var]):
    # mayb apply the nielson rules to front and back as is useful
    q = deque()
    subst = {}
    q.append((subst, ((x,y))))
    seen = set()
    n = 0
    while q:
        n += 1
        if n > 10:
            return
        (subst, (x,y)) = q.popleft()
        print("Nielson step:", x, y, subst)
        while x and y:
            a,b = x.pop(), y.pop()
            if a == b:
                continue
            else:
                # not equal. Do the junk
                # subst_pair copies btw
                x.append(a)
                y.append(b)
                p = (x,y)
                if not isinstance(a, Var) and not isinstance(b, Var):
                   pass # fail
                elif isinstance(a, Var) and isinstance(b, Var):
                    # both vars
                    z = freshvar()
                    q.append(({a : [b], **subst}, subst_pair(p, a, b ))) # assume equal
                    q.append(({b : [z,a] , **subst}, subst_pair(p, b, [z,a]) )) # a is prefix of b
                    q.append(({a : [z,b], **subst}, subst_pair(p, a, [z,b]) )) # b is prefix of a
                else:
                    if isinstance(b, Var):
                        a,b = b,a
                    # a is var, b is not
                    q.append(({a : [], **subst}, subst_pair((x,y), a, []))) # a is empty
                    #q.append(({a : [b], **subst}, subst_pair((x,y), a, [b]))) # a is empty
                    z = freshvar()
                    q.append(({a : [z,b], **subst}, subst_pair((x,y), a, [z,b]))) # b is prefix of a
                break
        else:
            if len(x) == 0 and len(y) == 0:
                yield subst
            elif len(y) == 0:
                if all(isinstance(v, Var) for v in x):
                    yield {**subst, **{v : [] for v in x}}
            elif len(x) == 0:
                if all(isinstance(v, Var) for v in y):
                    yield {**subst, **{v : [] for v in y}}

def canon_subst(subst, x):
    res = []
    for a in x:
        if isinstance(a, Var) and a in subst:
            subst[a] = Var(len(subst))
        else:
            res.append(a)
    return tuple(res)

def canon(p):
    x,y = p
    subst = {}
    x1 = canon_subst(subst, x)
    y1 = canon_subst(subst, y)
    return (x1,y1)


def compress(subst):
    res = {}
    for k,v in subst.items():
        s = []
        i = 0
        todo = list(reversed(v))
        while todo:
            x = todo.pop()
            if isinstance(x, Var) and x in subst:
                todo.extend(subst[x])
            else:
                s.append(x)
        res[k] = s
    return res

def cnielson(x : list[object | Var], y : list[object | Var]):
    for subst in nielson(x,y):
        yield {k:v for k,v in compress(subst).items() if not k.name.startswith("_")}

x,y,z = map(Var, "xyz")
assert list(cnielson([1,2], [1,2])) == [{}]
assert list(cnielson([1,2], [1,2,3])) == []
list(cnielson([x,2], [1,2]))
#assert list(nielson([x,2], [1,x])) == [] # doesn't terminate
assert list(cnielson([x,2], [1,2,3])) == []
list(cnielson([x,y], [1,2]))
list(cnielson([x,x], [1,2]))
list(cnielson([x,2], [2,x]))
#list(nielson([1,x], [1,2,y]))

Nielson step: [1, 2] [1, 2] {}
Nielson step: [1, 2] [1, 2, 3] {}
Nielson step: [Var(name='x'), 2] [1, 2] {}
Nielson step: [] [1] {Var(name='x'): []}
Nielson step: [Var(name='_1'), 1] [1] {Var(name='x'): [Var(name='_1'), 1]}
Nielson step: [Var(name='x'), 2] [1, 2, 3] {}
Nielson step: [Var(name='x'), Var(name='y')] [1, 2] {}
Nielson step: [Var(name='x')] [1, 2] {Var(name='y'): []}
Nielson step: [Var(name='x'), Var(name='_2'), 2] [1, 2] {Var(name='y'): [Var(name='_2'), 2]}
Nielson step: [] [1, 2] {Var(name='x'): [], Var(name='y'): []}
Nielson step: [Var(name='_3'), 2] [1, 2] {Var(name='x'): [Var(name='_3'), 2], Var(name='y'): []}
Nielson step: [Var(name='x')] [1] {Var(name='_2'): [], Var(name='y'): [Var(name='_2'), 2]}
Nielson step: [Var(name='x'), Var(name='_4'), 1] [1] {Var(name='_2'): [Var(name='_4'), 1], Var(name='y'): [Var(name='_2'), 2]}
Nielson step: [] [1] {Var(name='_3'): [], Var(name='x'): [Var(name='_3'), 2], Var(name='y'): []}
Nielson step: [Var(name='_5'), 1] [1] {Var(name='_

[{Var(name='x'): []},
 {Var(name='x'): [2]},
 {Var(name='x'): [2, 2]},
 {Var(name='x'): [2, 2, 2]},
 {Var(name='x'): [2, 2, 2, 2]}]

In [ ]:

def match_empty(xs):
    # all variables.
    return all(isinstance(x, Var) for x in xs)


    while x or y:
        a,b = x.pop(), y.pop()
        if a == b:
            continue
        else:
            break
    if len(x) == 0:
    if len(x) == 0 and len(y) == 0:
        return True
    elif len(x) == 0:
        return match_empty(y)
    elif len(y) == 0:
        return match_empty(x)
    a,b = x[0], y[0]
    if a == b: # TODO: turn into a loop
        return nielson(x[1:], y[1:])
    #elif x[-1] == y[-1]: Maybe only do this once at top level as fast
    #    return nielson(x[:-1], y[:-1])
    elif not isinstance(x[0], Var) and not isinstance(y[0], Var) and x[0] != y[0]:
        return False
    #elif not isinstance(x[-1], Var) and not isinstance(y[-1], Var) and x[-1] != y[-1]:
    #    return False
    elif isinstance(a, Var) and isinstance(b, Var):
        if nielson(x[1:], y[1:]): # assume equal
            return True
        z = freshvar()
        if nielson(subst(x[1:], b, [a, z]), subst(y[1:], b, [a, z])):
            return True
        elif nielson(subst(x[1:], a, [b, z]), subst(y[1:], a, [b, z])):
            return True
    if instance(b, Var):
        a,b = b,a
        x,y = y,x
    if nielson(subst(x[1:], a, [b]), subst(x[1:], a, [b])):
        return True
    z = freshvar()
    if nielson(subst(y[1:], b, [a,z]), subst(y[1:], b, [a,z])):
        return True


In [5]:
x = [1,2,3]
y = [3,4]
while x and y:
    a,b = x.pop(), y.pop()
x,y

([1], [])

In [ ]:
def acunify(vs : list[object | Var]):
    

In [ ]:




    t,s = x[0], y[0]
    match t,s:
        

def acunify(x, y):
    
def nielson(vs : list[smt.ExprRef], x : smt.SeqRef, y : smt.SeqRef):




For eunify, I should have a term generator to generators all associations of concats.



In [ ]:
import cvc5.pythonic as cvc5

Shape = cvc5.SeqSort(cvc5.IntSort())
n,m = cvc5.Ints("n m")
cvc5.Lambda([n], n)
cvc5.Lambda([n,m], n)
cvc5.ArraySort(cvc5.IntSort(), Shape)


SMTException: First argument must be an SMT array expression

In [90]:
import libmata

ModuleNotFoundError: No module named 'libmata'

# mirage

a multilevel superopitmizer for tensor programs

complex memory hiearchy

1 TB/s
10 TB/s
100TB/sw

~100 sm streaming multiplrecessor

cudea cores -> rwegister file

pytorch - rmsnorm 
softmax
matmul

manually impelemtn optimized kernels

multi-lvel superopimzier

TASO '19 and PET '21
TVM and Ansor '20

mugraph
graph styel representation
vertices are tensor ocmputation
edges are inteedmiate results

thread blokc graph

cude cores - trheead graph

Transformation rules Gpast -> Gopt

generate all mugraphs
filter by equivalence verifier
opmtizatie
tensor layouts memory palnnign operator schuedling.
Pick fastest


brute generation
expression guided pruning

asbtract expression
sum64()


sum(i, mul(x,y)) = mul(sum(i,x), y) ... Is this sensical?

equivbalence verififer. 
probablistic verifier - only LAX umrapgs. imperect soundness
fromal verifier - any hardware 

randopm inputs in finite fiels to examine ugraph eQUIVBALENCE
polynomial identity testing
schwartz zippel lemma. testing polynommials via random input. Huh.


foraml verifier. Noit complete because rules are probably enough.
Unity OSDI '22. Giant axiom table?


What about using vampire?

mugraph optimizer



asbtract expressions
variable erasure

do rewriting over assuming all variables are applied to same value (diagonal project). NMore things becomes equal
Do summation reason assuming subexpressions don't depend on index. That's interesints.
Because they are doing pruning rather than proving.


graph rewriting


https://www.usenix.org/system/files/osdi25-wu-mengdi.pdf

https://github.com/NVIDIA/cutlass



pruning
https://www.youtube.com/watch?v=CKrQsMHUh8M OSDI '25 - Mirage: A Multi-Level Superoptimizer for Tensor Programs

It isn't 
Ah, good point. It isn't even clear these rewrites are dimensionally sound

forall x,y,i sum(i, div(x,y)) = div(sum(i,x),y)

https://github.com/mirage-project/mirage/blob/mpk/src/kernel/graph.cc kernel graph

https://github.com/mirage-project/mirage/blob/mpk/include/mirage/type.h

# interpreter

In [ ]:
import re
tokens = [
    ("WS", r"\s+"), 
    ("COMMENT", r"%[^\n\r]*"),
    ("LPAREN", r"\("),
    ("RPAREN", r"\)"),
    ("COMMA", r","),
    ("PERIOD", r"\."),
    ("IMPLY", r":-"),
    ("IDENT", r"[A-Za-z\-!=\+\*\_<>][A-Za-z0-9\-!=\+\*\_<>]*"),
    ("NUMBER", r"-?\d+(?:\.\d+)?")
    #("QUOTE", r"\|")
]

regex = "|".join(f"(?P<{name}>{regex})" for name,regex in tokens)
pattern = re.compile(regex)
def parse(s : str):
    it = pattern.finditer(s)
    def args():
        items = []
        for match_ in it:
            match match_.lastgroup:
                case "WS" | "COMMENT":
                    continue
                case "IDENT" | "NUMBER":
                    items.append([match_.group()] + expr())
                case "COMMA":
                    continue
                case "RPAREN":
                    return items
                case _:
                    raise ValueError(f"unexpected token {match_.group()}")
        raise ValueError("unbalanced paren")
    def expr():
        for match_ = next(it):
            match match_.lastgroup:
                case "WS" | "COMMENT":
                    continue
                case "IDENT":
                    ident = match_.group()
                    match_ = next(it)
                    if match_.lastgroup == "LPAREN":
                        return (ident, args())
        raise ValueError("unbalanced paren")
    # match sexp*
    out = []
    for match_ in it:
        match match_.lastgroup:
            case "WS" | "COMMENT":
                continue
            case _:
                out.append(expr())
    return out

In [38]:

p = iter(range(5))
for x in p:
    print("x", x)
    for y in p:
        print("y", y)

x 0
y 1
y 2
y 3
y 4


https://norvig.com/lispy.html
https://github.com/dhilst/lis.py
https://github.com/pavpanchekha/pylisp
Make a numpy interpreter
jax / pytorch
compile to xdsl
compile to llvm
compile to smt

In [8]:
from kdrag.parsers.sexp import parse
import operator
import functools
import numpy as np
parse("(+ 1 2 3 4)")

def expr(env, sexp):
    match sexp:
        case int() | float():
            return sexp
        case str():
            return env[sexp]
        case ["if", cond, then, otherwise]:
            return expr(env, then) if expr(env, cond) else expr(env, otherwise)
        case ["set!", name, value]:
            env[name] = expr(env, value)
        case ["lambda", [*args], body]:
            return lambda *argvals: expr({**env, **dict(zip(args, argvals))}, body)
        case ["quote", body]:
            return body
        case ["define-macro", name, [*args], body]:
            env["__macros"][name] = lambda *argvals: expr({**env, **dict(zip(args, argvals))}, body)
        case ["eval", body]:
            return expr(env, expr(env, body))
        case [".", obj, attr]:
            return getattr(expr(env, obj), attr) # attr is intrinsically quoted?
        case ["array", shape, *vals]:
            return np.array(vals).reshape(shape)
        case ["frame", shape, *vals]:
            raise NotImplementedError()
        case [op, *args]:
            if isinstance(op, str) and op in env["__macros"]:
                return expr(env, env["__macros"][op](*args))
            else:
                return expr(env, op)(*(expr(env, arg) for arg in args))

def stmt(env, sexp):
    match sexp:
        case ["define", name, value]:
            env[name] = expr(env, value)
        case _:
            print(expr(env, sexp))

def stmts(sexps):
    def myassert(x):
        assert x
    env = {"+": lambda *args: functools.reduce(operator.add, args),
           "print": print,
           "assert": myassert,
           "nil" : [],
           "true": True,
           "false": False,
           "-": operator.sub,
           "*": lambda *args: functools.reduce(operator.mul, args),
           "=": operator.eq,
           "<": operator.lt,
           ">": operator.gt,
           "<=": operator.le,
           ">=": operator.ge,
           "/": operator.truediv,
           "car": lambda x: x[0],
           "cdr": lambda x: x[1:],
           "cons": lambda x, xs: [x] + xs,
           "list": lambda *args: list(args),
           "map": lambda f, lst: list(map(f, lst)),
           "array": lambda shape, *vals: np.array(vals).reshape(shape),
           "reduce": lambda f, arr: f.reduce(arr),
           "np": np,
           "__macros" : {}
           }
    for sexp in sexps:
        stmt(env, sexp)
    return env

stmts(parse("""
(define x 10)
(define y 20)
(+ x y 30)
(print 17)
(assert true)
;(assert false)
((lambda (x) (+ x 1)) 10)
(+ (quote (1 2)) (quote (3 4)))
(cdr (quote (1 2 3 4)))
(car (quote (1 2 3 4)))
(map (lambda (x) (* x 2)) (quote (1 2 3 4 5 6 7 8 9 10)))
(eval (quote (+ 1 2)))
(array (2 5) 1 2 3 4 5 6 7 8 9 10)
(array () 17)
((. np sum) (array (2 5) 1 2 3 4 5 6 7 8 9 10))
(define-macro when (cond body) (list (quote if) cond body (quote nil)))
(when false (print (quote it_worked)))

"""))


60
17
None
None
11
[1, 2, 3, 4]
[2, 3, 4]
1
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
3
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
17
55
None
[]


{'+': <function __main__.stmts.<locals>.<lambda>(*args)>,
 'print': <function print(*args, sep=' ', end='\n', file=None, flush=False)>,
 'assert': <function __main__.stmts.<locals>.myassert(x)>,
 'nil': [],
 'true': True,
 'false': False,
 '-': <function _operator.sub(a, b, /)>,
 '*': <function __main__.stmts.<locals>.<lambda>(*args)>,
 '=': <function _operator.eq(a, b, /)>,
 '<': <function _operator.lt(a, b, /)>,
 '>': <function _operator.gt(a, b, /)>,
 '<=': <function _operator.le(a, b, /)>,
 '>=': <function _operator.ge(a, b, /)>,
 '/': <function _operator.truediv(a, b, /)>,
 'car': <function __main__.stmts.<locals>.<lambda>(x)>,
 'cdr': <function __main__.stmts.<locals>.<lambda>(x)>,
 'cons': <function __main__.stmts.<locals>.<lambda>(x, xs)>,
 'list': <function __main__.stmts.<locals>.<lambda>(*args)>,
 'map': <function __main__.stmts.<locals>.<lambda>(f, lst)>,
 'array': <function __main__.stmts.<locals>.<lambda>(shape, *vals)>,
 'reduce': <function __main__.stmts.<locals>.<lambd

In [2]:
parse("""
(define x 10)
(define y 20)
(+ x y 30)
(print 17)
(assert true)
;(assert false)
((lambda (x) (+ x 1)) 10)
(+ (quote (1 2)) (quote (3 4)))
(cdr (quote (1 2 3 4)))
(car (quote (1 2 3 4)))
(map (lambda (x) (* x 2)) (quote (1 2 3 4 5 6 7 8 9 10)))
(eval (quote (+ 1 2)))
(array (2 5) 1 2 3 4 5 6 7 8 9 10)
(array () 17)
((. np sum) (array (2 5) 1 2 3 4 5 6 7 8 9 10))

""")

[['define', 'x', 10],
 ['define', 'y', 20],
 ['+', 'x', 'y', 30],
 ['print', 17],
 ['assert', 'true'],
 [['lambda', ['x'], ['+', 'x', 1]], 10],
 ['+', ['quote', [1, 2]], ['quote', [3, 4]]],
 ['cdr', ['quote', [1, 2, 3, 4]]],
 ['car', ['quote', [1, 2, 3, 4]]],
 ['map',
  ['lambda', ['x'], ['*', 'x', 2]],
  ['quote', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]],
 ['eval', ['quote', ['+', 1, 2]]],
 ['array', [2, 5], 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 ['array', [], 17],
 [['np', 'sum'], ['array', [2, 5], 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]]

In [ ]:
# https://youtu.be/YMUCpx6vhZM?si=25Olqlb8BLCitQ5W&t=1190
def expand(menv, sexp):
    match sexp:
        case ["let-syntax", bindings, body]:
            for name, value in bindings:
                menv[name] = eval_(menv, value)
        case ["syntax-local-value", _id]:# https://docs.racket-lang.org/reference/stxtrans.html#%28def._%28%28quote._~23~25kernel%29._syntax-local-value%29%29
            return menv[_id]
        # local-expand
        case [m, *args]:
            macro = menv.get(m)
            if macro is None:
                return [m, *(expand(env, arg) for arg in args)]
            else:
                expand(menv, macro(sexp))
        case _:
            return sexp

# racket fully expanded form




Can set of scopes be done declratively? Can I refold macros?

In [273]:
np.sum

<function sum at 0x760ee021d030>

In [ ]:
def expr(env, builder, sexp):
    

In [ ]:
import numpy as np

np.ufunc.reduce()

typed assembly language approach to bytecode?
Kind of an odd idea
overloading, tracing, ast sweep, bytecode, weird frame stuff (?), 

full sweep


# dep types
My stuff
smt dialect go into attributes.. yada yada dependent mlir?
good blog post
https://rschenck.com/docs/array-props.pdf  Verifying Properties of Index Arrays in a Purely-Functional Data-Parallel Language


# cost models
cache modeling
scallop neuro learning of

Roughly model of pipes?

https://dl.acm.org/doi/10.1145/3656452 Falcon: A Scalable Analytical Cache Model


Unison had a model.

  resource
insn(resource, time, )

Given programn, write prolog program to compute the time it would take.

pipeline_state()
cache_state(t, )



# futhark

`nix-shell -p futhark`
repl
c



# klr
https://github.com/leanprover/KLR
https://github.com/leanprover/TensorLib

In [207]:
! klr

klr [0.0.12]
KLR is an IR for NKI and other tensor-like languages in Lean.

USAGE:
    klr [SUBCOMMAND] [FLAGS]

FLAGS:
    -h, --help  Prints this message.
    --version   Prints the version.

SUBCOMMANDS:
    compile     Compile a NKI kernel
    eval-klr    Evaluate a kernel using a pure-Lean KLR interpreter. Outputs one
                npy file for each output.
    gather      Gather Python sources into an AST file
    info        Display information about a KLR file
    nki-to-klr  Compile NKI kernel to KLR
    trace       Trace Python to KLR
    typecheck   Run the type checker on a Python AST file


In [214]:
import klr.frontend as fe
def kernel_function(a, b):
  return a + b
kernel = fe.Kernel(kernel_function)
kernel.specialize(1, 2)
# Serialize the result
ba = kernel.serialize("/tmp/kernel.klr")
  # get a KLR abstract snytax tree
import klr.ast_nki
ast = fe.deserialize(ba)
ast

Kernel(entry='__main__.kernel_function', funs=[Fun(name='__main__.kernel_function', file='unknown', line=2, body=[Stmt(stmt=Stmt_ret(e=Expr(expr=Expr_binOp(op=<BinOp.Add: 9>, left=Expr(expr=Expr_var(name='a'), pos=Pos(line=2, column=9, lineEnd=2, columnEnd=10)), right=Expr(expr=Expr_var(name='b'), pos=Pos(line=2, column=13, lineEnd=2, columnEnd=14))), pos=Pos(line=2, column=9, lineEnd=2, columnEnd=14))), pos=Pos(line=2, column=2, lineEnd=2, columnEnd=14))], args=[Param(name='a', dflt=None), Param(name='b', dflt=None)])], args=[Arg(name='b', value=Expr(expr=Expr_value(value=Value_int(value=2)), pos=Pos(line=0, column=0, lineEnd=None, columnEnd=None))), Arg(name='a', value=Expr(expr=Expr_value(value=Value_int(value=1)), pos=Pos(line=0, column=0, lineEnd=None, columnEnd=None)))], globals=[])

In [213]:
! cat /tmp/kernel.klr

�������cKLR�����x__main__.kernel_function��
�x__main__.kernel_functiongunknown��������������aa�d�	������
�������d�	�������d���������	�aa����	�ab������ab�������d���������aa�������d��������

# llvm



llvmlite vs llvmpy


In [ ]:
module = ir.Module(name="testo")
# and declare a function named "fpadd" inside it
func = ir.Function(module, fnty, name="fpadd")

# Now implement the function
block = func.append_basic_block(name="entry")
builder = ir.IRBuilder(block)
a, b = func.args
result = builder.fadd(a, b, name="res")
builder.ret(result)

# Print the module IR
print(module)

; ModuleID = "testo"
target triple = "unknown-unknown-unknown"
target datalayout = ""

define double @"fpadd"(double %".1", double %".2")
{
entry:
  %"res" = fadd double %".1", %".2"
  ret double %"res"
}



In [ ]:
from kdrag.all import *
import llvmlite
def of_sort(s : smt.SortRef) -> llvmlite.ir.Type:
    if s == smt.BoolSort():
        return llvmlite.ir.IntType(1)
    elif isinstance(s, smt.BitVecSortRef):
        return llvmlite.ir.IntType(s.size())
    else:
        raise ValueError(f"unsupported sort {s}")

of_sort(smt.BitVecSort(32))

def of_expr(e : smt.ExprRef, env, builder) -> llvmlite.ir.Value:
    if smt.is_app(e):
        decl = e.decl()
        children = e.children()
        if decl.name() == "bvadd":
            lhs, rhs = (of_expr(c, env, builder) for c in children)
            return builder.add(lhs, rhs)
        elif smt.is_const(e):
            if smt.is_bv(e):
                return llvmlite.ir.Constant(of_sort(e.sort()), e.as_long())
        else:
            raise ValueError(f"unsupported decl {decl}")
    else:
        raise ValueError(f"unsupported expr {e}")

def func(name, args, e : smt.ExprRef):
    module = ir.Module(name="testo")
    fnty = ir.FunctionType(of_sort(e.sort()), [of_sort(a) for a in args])
    func = ir.Function(module, fnty, name=name)

    # Now implement the function
    block = func.append_basic_block(name="entry")
    builder = ir.IRBuilder(block)
    env = dict(zip(args, func.args))
    retval = of_expr(e, env, builder)
    builder.ret(retval)
    return module





# mlir


dependent mlir



https://github.com/opencompl/lean-mlir?tab=readme-ov-file

"just" printing the string.

https://gitlab.inria.fr/snoiry/mlir-list list lang tutorial

https://www.reddit.com/r/Compilers/comments/1nrj7gu/mlir_tutorial/
Repository with the code: https://github.com/rafasumi/mlir-tutorial
Lecture notes: https://github.com/rafasumi/mlir-tutorial/blob/main/assets/MLIR_tutorial_SBLP_2025.pdf

sum all array
vector add two arrays
blur
transpose (?)


In [1]:
%%file /tmp/myadd.mlir

module {
    func.func @myadd(%x : i32, %y : i32) -> i32 {
        %z = arith.addi %x, %y : i32
        return %z : i32
    }
}


Writing /tmp/myadd.mlir


In [182]:
! mlir-opt-20 /tmp/myadd.mlir -convert-to-llvm -o /tmp/add_llvm.mlir && cat /tmp/add_llvm.mlir

module {
  llvm.func @myadd(%arg0: i32, %arg1: i32) -> i32 {
    %0 = llvm.add %arg0, %arg1 : i32
    llvm.return %0 : i32
  }
}



In [3]:
! mlir-opt-20 --allow-unregistered-dialect --mlir-print-op-generic /tmp/myadd.mlir

"builtin.module"() ({
  "func.func"() <{function_type = (i32, i32) -> i32, sym_name = "myadd"}> ({
  ^bb0(%arg0: i32, %arg1: i32):
    %0 = "arith.addi"(%arg0, %arg1) <{overflowFlags = #arith.overflow<none>}> : (i32, i32) -> i32
    "func.return"(%0) : (i32) -> ()
  }) : () -> ()
}) : () -> ()



Hmm. Maybe I want an interpreter to z3


In [258]:
from xdsl.ir import Block, Region
from xdsl.printer import Printer
Block()

blk = Block(arg_types=[IntegerType(32)])
blk.args
builder = Builder(InsertPoint.at_end(blk))
i42 = builder.insert(ConstantOp(IntegerAttr(42, IntegerType(64))))
builder.insert(arith.AddiOp(blk.args[0], i42))
Printer().print(blk)


^0(%0 : i32):
  %1 = arith.constant 42 : i64
  %2 = arith.addi %0, %1 : i32


/tmp/ipykernel_323901/3024886619.py:10: DeprecationWarning: Please use type-specific print methods
  Printer().print(blk)


In [242]:
import xdsl.dialects.smt as smt
from xdsl_smt.traits.smt_printer import print_to_smtlib
dir(smt)
smt.BoolType()
smt.BitVectorType(32)
smt.FuncType([smt.BoolType()], smt.BoolType())
#print_to_smtlib()
const = smt.BvConstantOp(smt.BitVectorAttr(42,32))
import io

    # Create an empty StringIO object
string_buffer = io.StringIO()
print_to_smtlib(ModuleOp([const]), string_buffer)
string_buffer.getvalue()


'(declare-datatypes ((Pair 2)) ((par (X Y) ((pair (first X) (second Y))))))\n'

In [124]:
import xdsl
from xdsl.builder import Builder, InsertPoint
from xdsl.dialects.arith import AddiOp
from xdsl.dialects.builtin import ModuleOp, IntegerType, IntegerAttr
from xdsl.dialects.arith import ConstantOp

c0 = ConstantOp(IntegerAttr(0, 64))
c0
addi = AddiOp(c0.result, c0.result)
ModuleOp([addi])

ModuleOp(_operands=(), _operand_uses=(), results=(), _successors=(), _successor_uses=(), properties={}, attributes={}, regions=(Region(num_blocks=1),))

In [178]:
import xdsl.dialects.builtin as builtin
dir(builtin)
builtin.Block

xdsl.ir.core.Block

In [176]:
dir(arith)

['AddUIExtendedOp',
 'AddfOp',
 'AddiOp',
 'AndIOp',
 'AnyAttr',
 'AnyFloat',
 'AnyFloatConstr',
 'AnyOf',
 'Arith',
 'Attribute',
 'BitEnumAttribute',
 'BitcastOp',
 'CMPF_COMPARISON_OPERATIONS',
 'CMPI_COMPARISON_OPERATIONS',
 'CeilDivSIOp',
 'CeilDivUIOp',
 'ClassVar',
 'CmpfOp',
 'CmpiHasCanonicalizationPatterns',
 'CmpiOp',
 'Commutative',
 'ComparisonOperation',
 'ConditionallySpeculatable',
 'ConstantLike',
 'ConstantOp',
 'ContainerOf',
 'DenseIntOrFPElementsAttr',
 'DenseResourceAttr',
 'Dialect',
 'DivSIOp',
 'DivUIOp',
 'DivUISpeculatable',
 'DivfOp',
 'ExtFOp',
 'ExtSIOp',
 'ExtUIOp',
 'FPToSIOp',
 'FPToUIOp',
 'FastMathAttrBase',
 'FastMathFlag',
 'FastMathFlagsAttr',
 'FixedBitwidthType',
 'Float16Type',
 'Float32Type',
 'Float64Type',
 'FloatAttr',
 'FloatingPointLikeBinaryOpHasCanonicalizationPatternsTrait',
 'FloatingPointLikeBinaryOpHasFastReassociativeCanonicalizationPatternsTrait',
 'FloatingPointLikeBinaryOperation',
 'FloatingPointToIntegerBaseOp',
 'FloorDivSIOp'

In [ ]:
from xdsl.context import Context
from xdsl.parser import Parser
from xdsl.ir import OpResult
from xdsl.dialects import builtin, func, arith, scf
ctx = Context()
ctx.load_dialect(builtin.Builtin)
ctx.load_dialect(func.Func)
ctx.load_dialect(scf.Scf)
ctx.load_dialect(arith.Arith)

module_text = """
builtin.module {
  func.func @sum_of_squares(%n : index) -> index {
    %zero = arith.constant 0 : index
    %one = arith.constant 1 : index
    %res = scf.for %i = %zero to %n step %one iter_args(%acc_in = %zero) -> (index) {
      %square = arith.muli %i, %i : index
      %acc_out = arith.addi %acc_in, %square : index
      scf.yield %acc_out : index
    }
    func.return %res : index
  }
}
"""

module = Parser(ctx, module_text).parse_module()
module
print([op.name for op in module.walk()])

# PassPipeline

['builtin.module', 'func.func', 'arith.constant', 'arith.constant', 'scf.for', 'arith.muli', 'arith.addi', 'scf.yield', 'func.return']


In [269]:
modtext = r"""
module {
  func.func @is_positive(%x: i32) -> i32 {
    %c0 = arith.constant 0 : i32
    %cond = arith.cmpi sgt, %x, %c0 : i32
    %res = scf.if %cond -> (i32) {
      %c1 = arith.constant 1 : i32
      scf.yield %c1 : i32
    } else {
      scf.yield %c0 : i32
    }
    return %res : i32
  }
}
"""

module = Parser(ctx, modtext).parse_module()
print(module)
module.verify()
import xdsl.transforms.convert_scf_to_cf as scf2cf

scf2cf.ConvertScfToCf().apply(ctx, module)
module.verify()
print(module)

builtin.module {
  func.func @is_positive(%x : i32) -> i32 {
    %c0 = arith.constant 0 : i32
    %cond = arith.cmpi sgt, %x, %c0 : i32
    %res = scf.if %cond -> (i32) {
      %c1 = arith.constant 1 : i32
      scf.yield %c1 : i32
    } else {
      scf.yield %c0 : i32
    }
    func.return %res : i32
  }
}
builtin.module {
  func.func @is_positive(%x : i32) -> i32 {
    %c0 = arith.constant 0 : i32
    %cond = arith.cmpi sgt, %x, %c0 : i32
    cf.cond_br %cond, ^0, ^1
  ^0:
    %c1 = arith.constant 1 : i32
    cf.br ^2(%c1 : i32)
  ^1:
    cf.br ^2(%c0 : i32)
  ^2(%res : i32):
    cf.br ^3
  ^3:
    func.return %res : i32
  }
}


In [237]:
# https://github.com/xdslproject/xdsl/blob/main/docs/Toy/toy/compiler.py
ctx = Context()
from xdsl.dialects import builtin, func, arith, scf, cf, affine
from xdsl.transforms.canonicalize import CanonicalizePass
from xdsl.transforms.dead_code_elimination import DeadCodeElimination
ctx.load_dialect(affine.Affine)
ctx.load_dialect(arith.Arith)
ctx.load_dialect(builtin.Builtin)
ctx.load_dialect(func.Func)
ctx.load_dialect(scf.Scf)
ctx.load_dialect(cf.Cf)
mod = Parser(ctx, r"""
module {
  func.func @main(%c: i1) -> i32 {
    scf.if %c {
      %x = arith.constant 0 : i32
      return %x : i32
    } else {
      %y = arith.constant 1 : i32
      return %y : i32
    }
  }
}
""").parse_op()
mod.verify()
print(mod)
CanonicalizePass().apply(ctx, mod)
print(mod)
mod.verify()

VerifyException: Operation scf.if terminates block in single-block region but is not a terminator

In [147]:
mod.body.block

Block(_args=(), num_ops=0)

In [153]:
mod = ModuleOp([])
builder = Builder(InsertPoint.at_end(mod.body.block))
builder.insert(ConstantOp(IntegerAttr(42, 64)))

ConstantOp(_operands=(), _operand_uses=(), results=(<OpResult[i64] index: 0, operation: arith.constant, uses: 0>,), _successors=(), _successor_uses=(), properties={'value': IntegerAttr(value=IntAttr(data=42), type=IntegerType(64))}, attributes={}, regions=())

In [162]:
print(mod)

builtin.module {
  %0 = arith.constant 42 : i64
}


In [17]:
%%file /tmp/add.mlir
module {
  func.func @main() -> i32 {
    %c2 = arith.constant 2 : i32
    %c3 = arith.constant 3 : i32
    %sum = arith.addi %c2, %c3 : i32
    return %sum : i32
  }
}


Writing /tmp/add.mlir


In [175]:
! mlir-opt-20 /tmp/add.mlir \
  -convert-to-llvm \
  -reconcile-unrealized-casts \
  -o /tmp/add_llvm.mlir

In [173]:
! cat /tmp/add_llvm.mlir

module {
  llvm.func @main() -> i32 {
    %0 = llvm.mlir.constant(2 : i32) : i32
    %1 = llvm.mlir.constant(3 : i32) : i32
    %2 = llvm.mlir.constant(5 : i32) : i32
    llvm.return %2 : i32
  }
}



In [174]:
! mlir-translate-20 --mlir-to-llvmir /tmp/add_llvm.mlir -o /tmp/add.ll

In [41]:
%%file /tmp/silly.mlir

module {
"dialect.bar"(%x, %y) ({
}) : (i32,i32) -> ()
}

Overwriting /tmp/silly.mlir


In [42]:
! mlir-opt-20  --allow-unregistered-dialect /tmp/silly.mlir

/tmp/silly.mlir:3:15: error: use of undeclared SSA value name
"dialect.bar"(%x, %y) ({
              ^
/tmp/silly.mlir:3:19: error: use of undeclared SSA value name
"dialect.bar"(%x, %y) ({
                  ^


https://github.com/xdslproject/xdsl/blob/main/xdsl/ir/core.py
https://github.com/spcl/pymlir/blob/master/mlir/astnodes.py

In [ ]:
from dataclasses import dataclass

@dataclass(eq=False)
class BlockArgument(SSAValue[AttributeCovT], Generic[AttributeCovT]):
    block: Block
    index: int

@dataclass(eq=False, unsafe_hash=False, repr=False)
class Operation(_IRNode):
    name : str
    _operands: SSAValues = field(default=SSAValues())
    _operand_uses: tuple[Use, ...] = field(default=())
    """
    The uses for each operand.
    They are stored separately from the operands to allow for more efficient
    access to the operand SSAValue.
    """

    results: SSAValues[OpResult] = field(default=SSAValues())
    """The results created by the operation."""

    _successors: tuple[Block, ...] = field(default=())
    """
    The basic blocks that the operation may give control to.
    This list should be empty for non-terminator operations.
    """

    _successor_uses: tuple[Use, ...] = field(default=())
    """
    The uses for each successor.
    They are stored separately from the successors to allow for more efficient
    access to the successor Block.
    """

    properties: dict[str, Attribute] = field(default_factory=dict[str, Attribute])
    """
    The properties attached to the operation.
    Properties are inherent to the definition of an operation's semantics, and
    thus cannot be discarded by transformations.
    """

    attributes: dict[str, Attribute] = field(default_factory=dict[str, Attribute])
    """The attributes attached to the operation."""

    regions: tuple[Region, ...] = field(default=())
    """Regions arguments of the operation."""

    parent: Block | None = field(default=None)
    """The block containing this operation."""

    _next_op: Operation | None = field(default=None)
    """Next operation in block containing this operation."""

    _prev_op: Operation | None = field(default=None)
    """Previous operation in block containing this operation."""

    traits: ClassVar[OpTraits]

@dataclass(init=False, eq=False, unsafe_hash=False)
class Block(_IRNode, IRWithUses, IRWithName):
    _args: tuple[BlockArgument, ...]
    _first_op: Operation | None = field(repr=False)
    _last_op: Operation | None = field(repr=False)
    _next_block: Block | None = field(default=None, repr=False)
    _prev_block: Block | None = field(default=None, repr=False)
    parent: Region | None = field(default=None, repr=False)

@dataclass(init=False, eq=False, unsafe_hash=False)
class Region(_IRNode):
    _first_block: Block | None = field(default=None, repr=False)
    _last_block: Block | None = field(default=None, repr=False)
    parent: Operation | None = field(default=None, repr=False)



Do I want everything to have labels?

In [ ]:
from dataclasses import dataclass, field

@dataclass
class Operation():
    name : str
    operands : list['SSAValue'] = field(default_factory=list)
    regions : list["Region"] = field(default_factory=list)
    attributes : dict[str, object] = field(default_factory=dict)
    properties : dict[str, object] = field(default_factory=dict)
    num_results : int = 1


    def __repr__(self):
        return f"{self.name} {", ".join(map(repr,self.operands))}"
    def __getitem__(self, i):
        assert 0 <= i < self.num_results
        return OpResult(self, i)

@dataclass
class Block():
    label : str
    arguments : list['BlockArgument']
    operations : list[Operation]

    def __repr__(self):
        return f"^{self.label}({', '.join(map(repr,self.arguments))}):\n" + \
               '\n'.join(f"  {repr(op)}" for op in self.operations)

@dataclass
class Region():
    blocks : list[Block] = field(default_factory=list)

    def __repr__(self):
        return f"{{{'\n'.join(map(repr,self.blocks))}}}"

@dataclass()
class BlockArgument():
    block: Block
    index: int

@dataclass
class OpResult:
    operation : Operation
    index : int

type SSAValue = OpResult | BlockArgument

Region()
foo = Block("foo", [], [])
def module(r : Region) -> Operation:
    return Operation(
        "builtin.module",
        regions=(r,),
    )
def func(name : str, args : list[BlockArgument], body : Region) -> Operation:
    return Operation(
        "func.func",
        regions=[body],
        attributes={"sym_name" : name}
    )
def const_i32(value : int) -> Operation:
    return Operation(
        "arith.constant",
        attributes={"value" : value, "type" : "i32"},
        num_results=1
    )
    
module(Region())

builtin.module 

## linalg
https://www.stephendiehl.com/posts/mlir_linear_algebra/
https://mlir.llvm.org/docs/Dialects/Linalg/
https://mlir.llvm.org/docs/Tutorials/transform/Ch0/

In [ ]:
%%file /tmp/matmul.mlir


module {
    func.func @mymatmul(%A: memref<4x4xf32>, %B: memref<4x4xf32>, %C: memref<4x4xf32>) {
        linalg.matmul 
            ins(%A, %B : memref<4x4xf32>, memref<4x4xf32>)
            outs(%C : memref<4x4xf32>) -> memref<4x4xf32>
        return 
    }
}


Overwriting /tmp/matmul.mlir


In [15]:
%%file /tmp/matmul.mlir

module {
    func.func @matmul(
    %A: memref<8x10xf32>,
    %B: memref<10x16xf32>,
    %C: memref<8x16xf32>
) {
    linalg.matmul ins(%A, %B : memref<8x10xf32>, memref<10x16xf32>) outs(%C : memref<8x16xf32>)
    return
}
}

Overwriting /tmp/matmul.mlir


-convert-linalg-to-loops  -convert-linalg-to-affine

In [16]:
! mlir-opt-20 /tmp/matmul.mlir -convert-linalg-to-loops -o /tmp/matmul_loops.mlir && cat /tmp/matmul_loops.mlir

module {
  func.func @matmul(%arg0: memref<8x10xf32>, %arg1: memref<10x16xf32>, %arg2: memref<8x16xf32>) {
    %c0 = arith.constant 0 : index
    %c8 = arith.constant 8 : index
    %c1 = arith.constant 1 : index
    %c16 = arith.constant 16 : index
    %c10 = arith.constant 10 : index
    scf.for %arg3 = %c0 to %c8 step %c1 {
      scf.for %arg4 = %c0 to %c16 step %c1 {
        scf.for %arg5 = %c0 to %c10 step %c1 {
          %0 = memref.load %arg0[%arg3, %arg5] : memref<8x10xf32>
          %1 = memref.load %arg1[%arg5, %arg4] : memref<10x16xf32>
          %2 = memref.load %arg2[%arg3, %arg4] : memref<8x16xf32>
          %3 = arith.mulf %0, %1 : f32
          %4 = arith.addf %2, %3 : f32
          memref.store %4, %arg2[%arg3, %arg4] : memref<8x16xf32>
        }
      }
    }
    return
  }
}



Affine manipulations

In [ ]:

from kdrag.all import *

# integer set
Loop2 = smt.ArraySort(smt.IntSort(), smt.IntSort(), smt.BoolSort())

# loop swapping

def Interval(start,end):
    return smt.Lambda([i], smt.And(start <= i, i < end))

smt.Lambda([i,j], Interval(0,10)(i) * Interval(0,i)[j])

Family = smt.ArraySort(smt.IntSort(), smt.ArraySort(smt.IntSort(), smt.IntSort()))

smt.Tuple(smt.IntSort(), smt.IntSort())


def is_family(): ...
def is_set(): ...

def lift(s1 : Family) -> Loop2 : # uncurry
    return smt.Lambda([i,j], s[i][j])






## diehl tutorial
https://www.stephendiehl.com/posts/mlir_introduction/
https://github.com/sdiehl/numpile/blob/master/numpile.py


In [4]:
%%file /tmp/simple.ll
define i32 @main() {
    ret i32 42
}

Writing /tmp/simple.ll


In [6]:
%%bash
llc-20 -filetype=obj --relocation-model=pic /tmp/simple.ll -o /tmp/simple.o
clang-20 -shared -fPIC /tmp/simple.o -o /tmp/libsimple.so

In [7]:
import ctypes

module = ctypes.CDLL("/tmp/libsimple.so")

module.main.argtypes = []
module.main.restype = ctypes.c_int

print(module.main())

42


In [11]:
%%file /tmp/simple.mlir
func.func @loop_add() -> (index) {
    %init = index.constant 0
    %lb = index.constant 0
    %ub = index.constant 10
    %step = index.constant 1

    %sum = scf.for %iv = %lb to %ub step %step iter_args(%acc = %init) -> (index) {
        %sum_next = arith.addi %acc, %iv : index
        scf.yield %sum_next : index
    }

    return %sum : index
}

func.func @main() -> i32 {
    %out = call @loop_add() : () -> index
    %out_i32 = arith.index_cast %out : index to i32
    func.return %out_i32 : i32
}


Writing /tmp/simple.mlir


In [14]:
%%bash
mlir-opt-20 /tmp/simple.mlir \
  --convert-func-to-llvm \
  --convert-math-to-llvm \
  --convert-index-to-llvm \
  --convert-scf-to-cf \
  --convert-cf-to-llvm \
  --convert-arith-to-llvm \
  --reconcile-unrealized-casts \
  -o /tmp/example_opt.mlir

In [15]:
! mlir-cpu-runner-20 /tmp/example_opt.mlir -e main  -entry-point-result=i32

45


In [ ]:
%%bash
mlir-translate-20 simple_opt.mlir -mlir-to-llvmir -o simple.ll
llc-20 -filetype=obj --relocation-model=pic simple.ll -o simple.o
clang-20 -shared -fPIC simple.o -o libsimple.so


In [ ]:
from mlir import ir

with ir.Context() as ctx:
    module = ir.Module.parse(open("input.mlir").read())
    module.operation.print(print_generic_op_form=True)


# cutlass
https://docs.nvidia.com/cutlass/latest/media/docs/pythonDSL/quick_start.html